### ISSUE TITLE
local_path_root is not reset

### ISSUE THREAD

**Issue by hoodie** [sunng87/handlebars-rust#104]
Hi there,
it seems to me that after a `{{/each}}`, `{{/with}}` or `{{/if}}` the `local_path_root` should be reset to what it was before entering the block, instead it remains the same path as inside the block ([as demonstrated here](https://github.com/hoodie/handlebars-rust/tree/bug/local_path_root), `cargo run --example render`).

Is this expected behavior?

**Comment by sunng87** [comment]
Good catch! I will fix this asap.

**Comment by sunng87** [comment]
The current `local_path_root` mechanism may not work well with nested `each` when referencing value like `../../a`. I decide to drop it for a new implementation in next release.

**Comment by sunng87** [comment]
This should be fixed in 0.21
