### ISSUE TITLE
Bad error messages

### ISSUE THREAD

**Issue by tiffany352** [sunng87/handlebars-rust#108]
In general, it seems like every malformed template results in an error message containing only "TemplateError" or "RenderError", and never any actually useful information. There are fields in the error messages for this stuff, but it doesn't look like they are used.

**Comment by sunng87** [comment]
TemplateError contains some detailed information with line number and error type. You may call description() on `TemplateError` and `RenderError` to get information. 

https://github.com/sunng87/handlebars-rust/blob/master/src/error.rs

**Comment by tiffany352** [comment]
It looks like my issue is actually with handlebars-iron's error structs. No matter what I do, including calling description(), the SourceError returned by reload() always gives me only the vague "TemplateError". I also have the same problem with the RenderError that gets returned by the HandlebarsEngine middleware. I do not understand why .description() and Display on SourceError behave this way, all it does is forward calls to the inner error message.

**Comment by sunng87** [comment]
@tiffany352 Have you tried to print the error via debug formatter `{:?}` ? It should prints inner error as in my updated example: https://github.com/sunng87/handlebars-iron/blob/master/examples/error.rs

**Comment by tiffany352** [comment]
That does work.
