### ISSUE TITLE
Use a faster HTML escape

### ISSUE THREAD

**Issue by Razican** [sunng87/handlebars-rust#109]
After the study by @lise-henry in her [article](https://lise-henry.github.io/articles/optimising_strings.html), I think it would be wise to implement it instead of the [current method](https://github.com/sunng87/handlebars-rust/blob/8c0102f9edf7c38e248cc5a335532bb9c9737c21/src/registry.rs#L28). I did some studies myself to try to do it in XML file escaping (not sure if that's for this case, though) and I got to [this version](https://github.com/SUPERAndroidAnalyzer/super/blob/c3e8a723b96743b74297b1798df174549e3fa142/src/results/mod.rs#L813).

**Comment by sunng87** [comment]
@Razican Thank you for this link! Current implementation is pretty straight forward. Would you like to make a pull request for this?

**Comment by Razican** [comment]
Sure!

**Comment by sunng87** [comment]
Implemented in #118
