### ISSUE TITLE
Dangerous decisions for  Helpers

### ISSUE THREAD

**Issue by mrLSD** [sunng87/handlebars-rust#111]
For Helpers examples (everywhere at handlebars examples and documentations) you suggest dangerous decision. For example:

https://github.com/sunng87/handlebars-rust/blob/master/examples/render.rs#L32-L48

What is it if no any parameters or less?
What if wrong parameters type?
What if `try!` invoked, what our **end user** seeing?

It is dangerous for real world projects.

My suggestion:
to emphasize developers to strong type and parameters checking.
For example:
```
fn rank_helper(_: &Context,
               h: &Helper,
               _: &Handlebars,
               rc: &mut RenderContext)
               -> Result<(), RenderError> {
    if h.params().len() == 2 {
        let value0 = h.param(0).unwrap().value();
        let value1 = h.param(1).unwrap().value();
        if value0.is_64() && value1.is_array() {
            let rank = value0.as_u64().unwrap() as usize;
            let teams = value1.as_array().unwrap();
            let total = teams.len();
            if rank == 0 {
                try!(rc.writer.write("champion".as_bytes()));
            } else if rank >= total - 2 {
                try!(rc.writer.write("relegation".as_bytes()));
            } else if rank <= 2 {
                try!(rc.writer.write("acl".as_bytes()));
            }
        } else {
            // Do somthing with that
        }
    } else {
        // Do somthing with that
    }
    Ok(())
}
```

**Comment by sunng87** [comment]
Hi @mrLSD , first I agree with you that this piece of code can be dangerous to real projects. It's not recommend to use `unwrap` without fallback. I just updated example in 88f9536.
