### ISSUE TITLE
Subexpressions not  working

### ISSUE THREAD

**Issue by mrLSD** [sunng87/handlebars-rust#115]
I got your example and template for it:
https://github.com/sunng87/handlebars-rust/blob/master/examples/render/template.hbs

And I trying add to end of file:
```
{{format "Test" }}
{{format (format "Text") }}
```

and got error:
`Error rendering "table" line 20, col 1: subexpression generates invalid value`

Documentation:
http://handlebarsjs.com/expressions.html#subexpressions

**Comment by sunng87** [comment]
this is because `format` generated text `Text pts` will be treated as a variable instead of a JSON string literal. 

If you change `format` to generate `"{} pts"`, it will work.

**Comment by mrLSD** [comment]
Let's imagine situation:
helpers:
* helper1 param1
* helper2 param1

Handlebars template:
```
{{ helper1 "John" }}
{{ helper2 "Jack" }}
{{ helper1 (helper2 "Jack") }}
{{ helper2 (helper1 "John") }}
```

Rendered:

> Hello, John
> Jack how are you?
> Hello, Jack how are you?
> Hello, John how are you?

It's an idiomatic way for Handlebars subexpression.

I need the example for rust-handlebars code for that.

**Comment by sunng87** [comment]
OK. I verified handlebarsjs and handlebars-java implementation. It seems they treat subexpression results as string literal directly. 

Then I will change the behaviour in handlebars-rust.
