### ISSUE TITLE
Nice to have: A macro to include the templates in the binary during compile-time

### ISSUE THREAD

**Issue by golddranks** [sunng87/handlebars-rust#116]
To be sure, I'm NOT speaking about having templates as macros, or something like that, as this crate is emphatically classifies that as a non-goal in it's README.

However, I think it'd be nice to have a macro that embeds the templates into the resulting binary. Diesel has a similar macro for embedding the SQL migration files used to setup the database: http://docs.diesel.rs/diesel/macro.embed_migrations!.html

At the moment, such macro would require a separate crate (For example, Diesel has the crate `diesel-codegen`), and using the nightly to build, but with the story for next-gen macros unfolding, I think this kind of a macro will become relevant.

**Comment by sunng87** [comment]
I guess `include_str` in rust stdlib might work for you?
https://doc.rust-lang.org/std/macro.include_str.html

**Comment by golddranks** [comment]
Ah, that indeed works. Thank you.
