### ISSUE TITLE
Update to pest 1.0. (once it's out)

### ISSUE THREAD

**Issue by dragostis** [sunng87/handlebars-rust#117]
I've updated pest some time ago with [non-atomic rules](http://dragostis.github.io/pest/pest/macro.grammar.html#non-atomic-rules-). This should make the implementation easier without needing to alter the token stream. Let me know if you need any help.

**Comment by sunng87** [comment]
Thank you @dragostis . Updating pest has been in my mind for a while. I will start upgrade once I find time.

**Comment by dragostis** [comment]
@sunng87 I took a look at the project with the idea of doing a PR but got a little tangled up in the details. Provided it wasn't a hard thing to accomplish, I could follow some simple directions, but I guess it probably involves changing the grammar to some degree which I wouldn't want to screw up.

**Comment by dragostis** [comment]
I guess it's better to wait until pest 1.0 comes out in a fews weeks or so. (pending macros 1.1, but there's also some work left to do)

**Comment by sunng87** [comment]
Nice! BTW, will macros 1.1 work on stable channel?

**Comment by dragostis** [comment]
They are going to be stabilized soon. :)

**Comment by dragostis** [comment]
I've released an RC for pest 1.0. The only thing blocking the 1.0 release is making sure it works great with Handlebars. 😄

**Comment by sunng87** [comment]
@dragostis I've had master branch updated to latest pest RC. I confirm it works perfect with handlebars. Looking forward to the 1.0 release!
