### ISSUE TITLE
Chained else expression

### ISSUE THREAD

**Issue by sunng87** [sunng87/handlebars-rust#12]
Support syntax

``` handlebars
{{#if ...}}
{{else if ...}}
{{else}}
{{/if}}
```

https://github.com/wycats/handlebars.js/pull/892

**Comment by golddranks** [comment]
Is there any workaround currently? I'd like to use this, but unfortunately I'm currently too busy to contribute.

**Comment by golddranks** [comment]
Oops the obvious workaround works. I had an unrelated syntax error because of a typo, which made me thing that nesting wouldn't work.

    {{#if var1}}
        ...
    {{ else }}{{#if var2}}
        ...
    {{ else }}
        ...
    {{/if}}{{/if}}

**Comment by sunng87** [comment]
Yes.

To support chained else, we may need an update in current parser and helper definition because `{{else if ...}}` is incompatible with current model.

**Comment by rousan** [comment]
Hey @sunng87, any progress on this issue?

**Comment by sunng87** [comment]
@rousan sorry, there is no progress for now.

**Comment by rousan** [comment]
so, is there any way to add some patches like adding a block helper? It would very helpful then.

**Comment by sunng87** [comment]
@rousan the helper system is totally open. You can register you own block/inline helpers with our API. Checkout examples if you like.

For this chained else, some work needs to be done on the parser and our template structure to support chained inverse template segment. I will probably add support in future releases.

**Comment by shchemelevev** [comment]
+1 to this request

**Comment by shujaatak** [comment]
> @rousan the helper system is totally open. You can register you own block/inline helpers with our API. Checkout examples if you like.
> 
> For this chained else, some work needs to be done on the parser and our template structure to support chained inverse template segment. I will probably add support in future releases.

Anxiously waiting for this feature!
Any updates?

**Comment by sunng87** [comment]
@shujaatak Unfortunately there is no progress for this feature. Contributions are welcomed for this.

**Comment by jqiris** [comment]
Any updates?

**Comment by sunng87** [comment]
Fixed in #629

**Comment by sunng87** [comment]
Released in 5.1.0
