### ISSUE TITLE
Extended helper module

### ISSUE THREAD

**Issue by sunng87** [sunng87/handlebars-rust#126]
I'm going to provide a set of helpers that will be useful to daily development. These helpers will be enabled via a feature called `ext-helpers`. Developers can pick up some of these helpers in their application.

## Number comparison 

- [x] `if-eq`
- [x] `if-neq`
- [x] `if-gt`
- [x] `if-lt`
- [x] `if-gte`
- [x] `if-lte`
- [x] `if-even`
- [x] `if-odd`

## String transform

- [ ] `prefix`
- [ ] `suffix`
- [ ] `join`
- [ ] `uppercase`
- [ ] `lowercase`
- [ ] `capitalize`
- [ ] `substring`

## Array

- [ ] `if-has`
- [ ] `if-not-has`
- [ ] `length`

**Comment by sunng87** [comment]
We will pick some helpers from:
https://github.com/helpers/handlebars-helpers#helpers

**Comment by killercup** [comment]
I tried writing a more generic kind of helper, `gt` (basically `let gt = |x, y| x > y;`), to be used as a subexpression. Having helpers like that would allow you to write much more complex ifs.

Is that currently possibly? How can a helper return a value other than writing to the context?

This is what I have currently:

```rust
fn gt(h: &Helper, _: &Handlebars, rc: &mut RenderContext) -> Result<(), RenderError> {
    let first = h.param(0).map(|x| x.value()).map(|x| x.as_u64()).ok_or_else(|| RenderError::new("`gt` requires two parameters"))?;
    let second = h.param(1).map(|x| x.value()).map(|x| x.as_u64()).ok_or_else(|| RenderError::new("`gt` requires two parameters"))?;
    let result = first > second;

    rc.writer().write(result.into_bytes().as_ref())?;

    Ok(())
}
```

**Comment by sunng87** [comment]
I can understand you want simple and lightweight helper like a javascript function. Handlebars takes subexpression render result as json literal or variable name. To have simple helper like `let gt = |x, y| x > y;`, we just need a wrapper to do two things: 

1. Extract x,y from helper params, check type or report error
2. Write the return value to writer

Perhaps we can wrap it in a macro like `helper!(|x: u64, y: u64| x > y)`, which expands to 

```
|h: &Helper, _: &Handlebars, rc: &mut RenderContext|-> Result<(), RenderError> {
    let x = h.param(0).map(|x| x.value()).map(|x| x.as_u64()).ok_or_else(|| RenderError::new("`gt` requires two parameters"))?;
    let y = h.param(1).map(|x| x.value()).map(|x| x.as_u64()).ok_or_else(|| RenderError::new("`gt` requires two parameters"))?;
    let result = x > y;

    rc.writer().write(result.into_bytes().as_ref())?;

    Ok(())
}
```

We still need `u64` type provided by user to generate the expected type.

WDYT?

**Comment by killercup** [comment]
Oh, I see! There's always a JSON serialization in between, even when calling helpers. That's pretty clever, actually!

So, the problem with my code above was just the line with the writer, as you can't transform a `bool` to a `&[u8]` with knowing the encoding. It compiles and seems to work with this:

```rust
rc.writer().write(json!(result).to_string().into_bytes().as_ref())?;
```

Or, using serde_json's conveniences:

```
serde_json::to_writer(rc.writer(), json!(result))?;
```

I'll try to write a small lib with that macro you described.

**Comment by killercup** [comment]
Okay, I started a repo here: https://github.com/killercup/handlebars-helpers-rust

It's very bare-bones right now, but has a macro to easily define helpers and already defines a few simple ones.

Sadly, I still have some issues getting the correct data type from a subexpression. Apparently, the param that contains the result from the subexpression (gt 5 3) is of type String("true") instead of Bool(true). This means the not helper doesn't work. I've opened in issue for that in <https://github.com/killercup/handlebars-helpers-rust/issues/1>, maybe you can have a look?

**Comment by sunng87** [comment]
Helper macro is now a part of handlebars-rust. And some helpers were added:

* gt
* gte
* lt
* lte
* eq
* ne
* not
* or
* and

It is recommended to use them as subexpression with `if`.

```handlebars
{{#if (eq value 1)}}
...
{{/if}}
```

It should be easier to develop helpers. Let me close this.

**Comment by cedeber** [comment]
Hi, would be nice to have some doc somewhere regarding these helpers. Maybe just copy the previous comment to the README? Thanks.
