### ISSUE TITLE
Error building serde_types feature

### ISSUE THREAD

**Issue by Razican** [sunng87/handlebars-rust#132]
I'm getting issues building with `--no-default-features --features=serde_type`:

```
error[E0432]: unresolved import `grammar::Rdp`
  --> src/template.rs:14:15
   |
14 | use grammar::{Rdp, Rule};
   |               ^^^ no `Rdp` in `grammar`

error[E0432]: unresolved import `grammar::Rule`
  --> src/template.rs:14:20
   |
14 | use grammar::{Rdp, Rule};
   |                    ^^^^ no `Rule` in `grammar`

error[E0432]: unresolved import `grammar::Rdp`
  --> src/context.rs:10:15
   |
10 | use grammar::{Rdp, Rule};
   |               ^^^ no `Rdp` in `grammar`

error[E0432]: unresolved import `grammar::Rule`
  --> src/context.rs:10:20
   |
10 | use grammar::{Rdp, Rule};
   |                    ^^^^ no `Rule` in `grammar`

error: the type of this value must be known in this context
   --> src/template.rs:179:15
    |
179 |         match name_node.rule {
    |               ^^^^^^^^^^^^^^

error: the type of this value must be known in this context
   --> src/template.rs:196:12
    |
196 |         if param.rule == Rule::param {
    |            ^^^^^^^^^^

error: the type of this value must be known in this context
   --> src/template.rs:237:26
    |
237 |         let key = source[name.start..name.end].to_owned();
    |                          ^^^^^^^^^^

error: the type of this value must be known in this context
   --> src/template.rs:250:25
    |
250 |         let p1 = source[p1_name.start..p1_name.end].to_owned();
    |                         ^^^^^^^^^^^^^

error: no method named `setup_builtins` found for type `registry::Registry` in the current scope
  --> src/registry.rs:76:11
   |
76 |         r.setup_builtins()
   |           ^^^^^^^^^^^^^^

error: aborting due to 5 previous errors

error: Could not compile `handlebars`.
```

Couldn't look on how to fix it, but for the future I think it would be useful to include better build tests. The issue happens with 0.24.1/0.24.2-pre but not with 0.22.

**Comment by sunng87** [comment]
Just remove `--no-default-features` and try again, :-)
This option is no longer needed in recent version.

**Comment by Razican** [comment]
True, but why are there default features if they are required for building?

**Comment by sunng87** [comment]
It's because there is another required feature in default feature set. Once you turn off it doesn't compile.

I will try to improve this feature management because I found it introduced some issues for testing.

**Comment by Razican** [comment]
I see that by default, it uses features `rustc_ser_type` and `partial4`. The thing is that if somebody does not want rustc_serialize type, it will be built in any case, that's why `--no-default-features` exists. Features should be optional always. You could probably ad `#[cfg(not(feature = "whatever"))]` in places where something should always be built except in the case of that feature, and in the code that must always be built, should be no feature flags.

**Comment by sunng87** [comment]
Thanks. I'm working on that.

**Comment by sunng87** [comment]
This should have been fixed in master.
