### ISSUE TITLE
Update to serde 0.9.0

### ISSUE THREAD

**Issue by dtolnay** [sunng87/handlebars-rust#134]
Rocket is using this crate and would like to use serde 0.9.0 :pray:

Here are the release notes: https://github.com/serde-rs/serde/releases/tag/v0.9.0

**Comment by sunng87** [comment]
Yes I'm working on that. Serde JSON 0.9 has some breaking API changes so it will take some time.

**Comment by sunng87** [comment]
@dtolnay Released in 0.25.0
