### ISSUE TITLE
Drop rustc_serialize support

### ISSUE THREAD

**Issue by sunng87** [sunng87/handlebars-rust#136]
Rustc_serialize support will sunset. There will be a 0.x version that use serde as default type system and allow rustc_serialize via feature flag. And in 1.0 release there will be no rustc_serialize for this library.

**Comment by sunng87** [comment]
Cargo is using handlebars with rustc_serialize so we probably won't drop it in near future.

**Comment by dtolnay** [comment]
@sunng87 I would encourage you to reconsider this. Cargo is very interested in moving to Serde-based handlebars. Quoting from https://github.com/rust-lang/cargo/pull/3682:

> This doesn't completely excise the dependency just yet as docopt still requires it along with handlebars. I'm sure though that in time those crates will migrate to serde!

Also according to the [Rust release milestone predictions](https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591?u=dtolnay), rustc-serialize is scheduled to be deprecated in next month's beta release.

**Comment by sunng87** [comment]
@dtolnay Thank you for pointing out this. Then I will definitely sunset rustc_serialize support in next release.
