### ISSUE TITLE
Nested each issue

### ISSUE THREAD

**Issue by LLBlumire** [sunng87/handlebars-rust#145]
I'm attempting to write a C++ code generator, and have encountered an issue where this, which works fine in handlebars.js does not work in handlebars-rust

```handlebars
{{#each variant}}
{{#each ../typearg}}{{#if @first}}template <{{/if}}{{this}}{{#if @last}}>{{else}},{{/if}}{{/each}}
{{/each}}
```

```js
{
    typearg: [ 'T' ],
    variant: [{ }, { }]
}
```

I'd expect this to output

```
template<T>
template<T>
```

as it does if run in handlebars.js, instead I am getting out

```
template<>
template<>
```

**Comment by LLBlumire** [comment]
at the moment I am doing a workaround of replacing `{{this}}` with `{{lookup ../typearg @index}}`

**Comment by sunng87** [comment]
Thank you for reporting. I just confirmed this behaviour on handlebarsjs. This should be a bug when resolving `this` in nested context. I will look into this issue this weekend.
