### ISSUE TITLE
Partial is rendered twice

### ISSUE THREAD

**Issue by euclio** [sunng87/handlebars-rust#146]
Not sure if this is an issue with the library or my syntax. I'm updating a project that I wrote from the legacy partial syntax to the new syntax.
I have three (simplified) templates like this:

```hbs
<!-- base.hbs -->
<html>
<body>
{{> layout}}
</body>
</html>
```

```hbs
<!-- blog.hbs -->
{{#> base}}

{{#*inline "layout"}}
<div>
{{#> content}}
Parent content
{{> otherHelper}}
{{/content}}
</div>
{{/inline}}

{{/base}}
```

```hbs
<!-- blog_post.hbs -->
{{#> blog}}

{{#*inline "content"}}
Child content
{{/inline}}

{{/blog}}
```
The problem is that the `otherHelper` helper gets rendered (and output) twice, and I cannot figure out why.

**Comment by sunng87** [comment]
The syntax for 

```handlebars
{{#> content}}
Parent content
{{> otherHelper}}
{{/content}}
```
is: if `content` partial not found, render the inner template. It seems my implementation rendered `{{> otherHelper}}` even when `content` is defined. This should be a bug. I will try to fix it this weekend.

**Comment by sunng87** [comment]
@euclio could you please verify if current `master` branch works for you?

**Comment by euclio** [comment]
Sure, I'm currently out of town but I can check when I'm back at my
computer.

**Comment by euclio** [comment]
Hm, having trouble testing this because I think that I'm getting a mismatch between `handlebars-iron` and `handlebars-rust`.

```
error[E0281]: type mismatch: the type `fn(&handlebars::Helper<'_>, &handlebars::Registry, &mut handlebars::RenderContext<'_>) -> std::result::Result<(), handlebars::RenderError> {helpers::join}` implements the trait `for<'r, 'r, 'r, 'r, 'r> std::ops::Fn<(&'r handlebars::Helper<'r>, &'r handlebars::Registry, &'r mut handlebars::RenderContext<'r>)>`, but the trait `for<'b, 'r, 'c, 'd, 'r> std::ops::Fn<(&'b handlebars::render::Helper<'r>, &'c handlebars::registry::Registry, &'d mut handlebars::render::RenderContext<'r>)>` is required (expected struct `handlebars::render::Helper`, found struct `handlebars::Helper`)
   --> src/routes.rs:169:51
    |
169 |     hbse.handlebars_mut().register_helper("join", Box::new(helpers::join));
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: required because of the requirements on the impl of `handlebars::helpers::HelperDef` for `fn(&handlebars::Helper<'_>, &handlebars::Registry, &mut handlebars::RenderContext<'_>) -> std::result::Result<(), handlebars::RenderError> {helpers::join}`
    = note: required for the cast to the object type `handlebars::helpers::HelperDef`
```

**Comment by sunng87** [comment]
Ops, this happens when you have different version of handlebars library. Could you please also checkout handlebars-iron and change it's depended handlebars to the master branch?

**Comment by euclio** [comment]
Ah. Just confirmed that it works on master, thanks! As a side note, why does `handlebars-iron` not expose `handlebars` as a `pub crate` if they're so tightly coupled?

**Comment by sunng87** [comment]
It seems I should. I'm not quite familiar with re-export at the moment. 

I'll close this for now.

**Comment by sunng87** [comment]
@euclio by the way do you have any links about re-export? I googled it only found a reddit thread says it's an undocumented technique. There was #67 about exporting JSON related crate. Maybe I can make decision for both.

**Comment by euclio** [comment]
I think there's an old issue where `pub extern crate` didn't work as expected, and you had to simulate the behavior by `pub use`ing the item imported by `extern crate`. However, these days it seems to work as expected. Not aware of any links beyond the [first edition of the rust book](https://doc.rust-lang.org/book/crates-and-modules.html#re-exporting-with-pub-use).

While I think that re-exporting `handlebars` is the right thing to do, because ideally `handlebars-iron` will be the only other dependency using it. I'm not sure that it makes as much sense for `serde`, since you'll need all your dependencies to use the same version of `serde` anyways, so it makes sense for a user to use their own `serde` dependency. See https://github.com/rust-lang/cargo/issues/2064 for some more discussion on this.

I can submit a PR for the re-export if you'd like, but it's a small change.

**Comment by sunng87** [comment]
Thank you @euclio , the patch is welcomed!
