### ISSUE TITLE
Upgrade to Serde 1.0

### ISSUE THREAD

**Issue by SergioBenitez** [sunng87/handlebars-rust#149]
This is blocking https://github.com/SergioBenitez/Rocket/pull/272.

**Comment by skariel** [comment]
@SergioBenitez just made a PR

**Comment by winding-lines** [comment]
This is so cool, I was also working on this :) Gotta love OSS.

**Comment by sunng87** [comment]
@winding-lines Thank you! Next time you can leave a message here to pick the feature. Patches are always welcomed in this project.
