### ISSUE TITLE
the trait bound `rustc_serialize::json::Json: serde::ser::Serialize` is not satisfied.

### ISSUE THREAD

**Issue by FractalMatt** [sunng87/handlebars-rust#154]
So, I'm still in the process of going through the many error messages left from upgrading all my libraries to support the gzip help you so kindly made for me. (Thanks again!)

And encoutering many errors that look like this:
error[E0277]: the trait bound `rustc_serialize::json::Json: serde::ser::Serialize` is not satisfied
   --> src/public.rs:431:41
    |
431 |                     let _ = res.set_mut(Template::new("public/reset_password", data))
    |                                         ^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `rustc_serialize::json::Json`
    |
    = note: required because of the requirements on the impl of `serde::ser::Serialize` for `std::collections::BTreeMap<std::string::String, rustc_serialize::json::Json>`
    = note: required by `hbs::Template::new`

**Is this due to the new version of Serde?  Does it require a new version of handlebars-rust?**
I'm using these versions and saw that the newest version if handlebars should support newest Serde:
handlebars = "^0.26"
handlebars-iron = "^0.24"

So probably me doing something wrong and not understanding what is involved with upgrading to use Serde?

**Is this error related?**
Seems like it might be.

error[E0281]: type mismatch: the type `fn(&handlebars::context::Context, &handlebars::render::Helper<'_>, &handlebars::registry::Registry, &mut handlebars::render::RenderContext<'_>) -> std::result::Result<(), handlebars::render::RenderError> {handlebars_markdown_helper::markdown_helper}` implements the trait `for<'r, 'r, 'r, 'r, 'r, 'r> std::ops::Fn<(&'r handlebars::context::Context, &'r handlebars::render::Helper<'r>, &'r handlebars::registry::Registry, &'r mut handlebars::render::RenderContext<'r>)>`, but the trait `for<'b, 'r, 'c, 'd, 'r> std::ops::Fn<(&'b handlebars::Helper<'r>, &'c handlebars::Registry, &'d mut handlebars::RenderContext<'r>)>` is required (expected a tuple with 3 elements, found one with 4 elements)
   --> src/main.rs:175:52
    |
175 |     let _ = handlebars.register_helper("markdown", Box::new(markdown_helper));
    |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: required because of the requirements on the impl of `handlebars::HelperDef` for `fn(&handlebars::context::Context, &handlebars::render::Helper<'_>, &handlebars::registry::Registry, &mut handlebars::render::RenderContext<'_>) -> std::result::Result<(), handlebars::render::RenderError> {handlebars_markdown_helper::markdown_helper}`
    = note: required for the cast to the object type `handlebars::HelperDef`

Would appreciate any insight as to what is going wrong

**Thanks again sunng!**

And to reply to your earlier comment, regarding Iron vs Rocket, Iron is great.. just not very well documented, whereas Rocket promises good documentation.  And supposedly has a little bit of a performance increase.

**Comment by sunng87** [comment]
Hi @FractalMatt, first of all handlebars 0.26.* and handlebars-iron 0.24.* does no longer support rustc_serialize. Could you please use serde or downgrade to handlebars-iron 0.23.* and verify again?

**Comment by FractalMatt** [comment]
Sorry it's late.. that was stupid.  Upgraded to serde_json and those errors are melting away.  Luckily the majority of the ones left and easy to fix :)

Now, what about this one:
error[E0281]: type mismatch: the type fn(&handlebars::context::Context, &handlebars::render::Helper<'_>, &handlebars::registry::Registry, &mut handlebars::render::RenderContext<'_>) -> std::result::Result<(), handlebars::render::RenderError> {handlebars_markdown_helper::markdown_helper} implements the trait for<'r, 'r, 'r, 'r, 'r, 'r> std::ops::Fn<(&'r handlebars::context::Context, &'r handlebars::render::Helper<'r>, &'r handlebars::registry::Registry, &'r mut handlebars::render::RenderContext<'r>)>, but the trait for<'b, 'r, 'c, 'd, 'r> std::ops::Fn<(&'b handlebars::Helper<'r>, &'c handlebars::Registry, &'d mut handlebars::RenderContext<'r>)> is required (expected a tuple with 3 elements, found one with 4 elements)
--> src/main.rs:175:52
|
175 | let _ = handlebars.register_helper("markdown", Box::new(markdown_helper));
| ^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: required because of the requirements on the impl of handlebars::HelperDef for fn(&handlebars::context::Context, &handlebars::render::Helper<'_>, &handlebars::registry::Registry, &mut handlebars::render::RenderContext<'_>) -> std::result::Result<(), handlebars::render::RenderError> {handlebars_markdown_helper::markdown_helper}
= note: required for the cast to the object type handlebars::HelperDef

There is so much going on there, that I can't see what's wrong.. maybe because it's so late. But do you see it?

I'm getting in bed, but to confirm, using serde instead of rustc_serialize fixed that error.  Thanks!

**Comment by sunng87** [comment]
This can be caused by imcompatible version of handlebars and handlebars-iron. Consider remove handlebars remove your Cargo.toml and use `handlebars-iron::handlebars::...`  instead, just like this: https://github.com/sunng87/handlebars-iron/blob/master/examples/server.rs#L16

**Comment by FractalMatt** [comment]
Hey, been working through other errors, no.. that didn't seem to do it :(

After that change, here's what I have that is handlebars related:
In toml:
handlebars = "^0.26"
handlebars-iron = "^0.24"
iron-error-router = "^0.3"
handlebars-markdown-helper = "^0.5"

In main.rs:
extern crate handlebars;
extern crate handlebars_markdown_helper;
extern crate handlebars_iron as hbs;

use handlebars_markdown_helper::markdown_helper;
use hbs::{HandlebarsEngine, DirectorySource, Template};
use hbs::handlebars::{Handlebars, RenderContext, RenderError, Helper};

And the snippet of code where I am actually calling it, this function is called from the 1st line of main:
fn route_server() -> Iron<Chain> {
    let mut handlebars = Handlebars::new();
    let _ = handlebars.register_helper("markdown", Box::new(markdown_helper));

It certainly looks like I'm using the newest version of everything...   am I missing something obvious here?

When I use "goto definition"  for register_helper I get:
pub fn register_helper(&mut self,
                           name: &str,
                           def: Box<HelperDef + 'static>)
                           -> Option<Box<HelperDef + 'static>> {
        self.helpers.insert(name.to_string(), def)
    }

pub trait HelperDef: Send + Sync {
    fn call(&self, h: &Helper, r: &Registry, rc: &mut RenderContext) -> Result<(), RenderError>;
}

and for markdown_helper:

pub fn markdown_helper(_: &Context, h: &Helper, _ : &Handlebars, rc: &mut RenderContext) -> Result<(), RenderError> {
	let markdown_text_var = try!(h.param(0).ok_or_else(|| RenderError::new("Param not found for helper \"markdown\"")));
	let markdown_text = markdown_text_var.value().render(); 
	let html_string = render_html(markdown_text);
	try!(rc.writer.write(html_string.into_bytes().as_ref()));
	Ok(())
}

Which does indeed seem like markdown_helper is missing  "r: &Registry" parameter?  Am I missing something?

I cleared my cargo.lock and clean and built again.. same error.  And double checked that I was using the newest version of those libraries.

Thanks again!

**Comment by sunng87** [comment]
`Registry` is just the internal name of `Handlebars`. I guess to root cause is `handlebars-markdown-helper` relies on an incompatible version of handlebars. There was a breaking change in the helper api and `handlebars-markdown-helper` didn't catch up.

**Comment by FractalMatt** [comment]
Thanks again!
