### ISSUE TITLE
Unserializable data presents no errors

### ISSUE THREAD

**Issue by kkartaltepe** [sunng87/handlebars-rust#161]
You can happily pass a template something that cannot be serialized (at runtime), and no errors will be thrown even if data is attempted to be accessed.

Example code is as follows
```rust
struct Unserializable(i8);

impl serde::ser::Serialize for Unserializable {
	fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
	where S: serde::ser::Serializer {
		Err(serde::ser::Error::custom("This instance cannot be serialized"))
	}
}

// Properly panics with the error
println!("{}", serde_json::to_string(&Unserializable(1)).unwrap());
// Runs and claims template was rendered without error
println!("Template Rendered: {}", handlebars.template_render("Some template {{this}}", &Unserializable(1)).unwrap());
```

This should propagate an error as the requirement that your data be serde serializable is violated. Its Exceedingly tricky to debug due to the lack of errors and in the case of potentially partially serializable data (if this is even possible in serde) access to serializable portions will silently fail as well (compose this with a known serializable at runtime type).

**Comment by sunng87** [comment]
Currently we treat unserializable data as `Json::Null`, which renders nothing to result.

```
pub fn to_json<T>(src: &T) -> Json
    where T: Serialize
{
    to_value(src).unwrap_or(Json::Null)
}
```

Let me think about whether we need to change to this or not.

**Comment by kkartaltepe** [comment]
I think that would work if it were slightly "smarter". Currently that will take a struct like the follow as a whole to just `Json::Null`.
```rust
#[derive(Serialize)]
struct composite {
    left: i32,
    right: Unserializable,
}
```

 if it were possible to push down that `Json::Null` to an element level so that it returned something like 
```json
{ "left": 1, "right": null }
```

I'm not sure if thats possible in serde but it would at least make more sense to the user (me). Instead of converting all data to null and providing no errors. Maybe adding in a `template_render_with_error()` which would instead propagate render errors and not interfere with existing semantics.

**Comment by sunng87** [comment]
I'm afraid this is not possible with serde_json's to_value. However, if the struct is in your hand, perhaps you can serialize to `Json::Null` instead of throwing an error.

I'm going to refactor `Context::wrap` to return `RenderError` when `serde_json::error::Error` caught, instead of eating the error quietly.

**Comment by kkartaltepe** [comment]
Awesome work, thanks!
