### ISSUE TITLE
Template rendering is very slow for large data

### ISSUE THREAD

**Issue by bruceg** [sunng87/handlebars-rust#166]
When rendering a template over a large vec (say, more than 1,000 items), handlebars-rust takes a very large amount of CPU time. Worse, extra data within the result (that may not be rendered) increases the time taken.

This sample program demonstrates the problem: https://gist.github.com/bruceg/410deb60468940c0b40a52814c2a2896 (run with two parameters, first is number of real rows, second is number of "dummy" rows that are not rendered). The run time is approximately O(N*(N*D)) where N is the number of rows to output, and D is the size of the dummy array. Doubling the number of rows produces a roughly four times increase in the total run time.

My guess would be the whole data is being copied (cloned) once per row somewhere. strace shows many calls to madvise(ADDR, SIZE, MADV_DONTNEED) between output writes, which seems to indicate large chunks of data being freed by the allocator.

**Comment by sunng87** [comment]
Thank you for reporting @bruceg , I will look into this issue this weekend. 
Which version of handlebars-rust you were using?

**Comment by bruceg** [comment]
It happens with both 0.27.0 and git master

**Comment by sunng87** [comment]
Just confirm this performance issue is introduced in 0.27, which clone `Context` for each helper execution:

Based on bench code in b2354be 

0.27 
test large_loop_helper ... bench: 496,376,347 ns/iter (+/- 148,433,745)

0.26.2
test large_loop_helper ... bench:   3,148,455 ns/iter (+/- 72,797)

@bruceg you can use handlebars 0.26.2 for now. And I'll find a solution to improve while keeping the new features in 0.27.

**Comment by sunng87** [comment]
Fixed in 0.28.0
