### ISSUE TITLE
escaped delimters yield escape characters in output

### ISSUE THREAD

**Issue by softprops** [sunng87/handlebars-rust#169]
I just ran into a use case where I needed my handle bars templates to yield `{{foo}}` in their output. This seems to be a feature in [handlebars js](https://github.com/wycats/handlebars.js/commit/c79c761460f7d08e3862c0c9992f65a799771851) and it does seem to be part of the [grammar here](https://github.com/sunng87/handlebars-rust/blob/6010f6a76b7cd8a7ee87136d7fc364c54c75e53a/src/grammar.rs#L48) However the delimiter is left behind in the rendered output (  `\\{{foo}}` ). Is there a way to both specify `{{foo}}`  in a handbars template and have it rendered in literal form `{{foo}}`?

**Comment by sunng87** [comment]
At the moment `\\` escape is not implemented. Let me find some time to work on it.

**Comment by softprops** [comment]
It looks like it's implemented in terms of avoid evaling tags but there's just a little bit more to strip off the escape pattern from the raw text tokens. I'm not sure if you can do that directly in pest but one example place where it may be possible is where the pest output is being unpacked. Looking around [this area](https://github.com/sunng87/handlebars-rust/blob/6010f6a76b7cd8a7ee87136d7fc364c54c75e53a/src/template.rs#L399-L401) to maybe do some kind of post processing. I think that's roughly what the [js impl did](https://github.com/wycats/handlebars.js/commit/c79c761460f7d08e3862c0c9992f65a799771851#diff-a13581e6dfc1c61c90703da188230cbcR8)

**Comment by sunng87** [comment]
Nice. For now we have escape check in pest grammar and `\\{{` will be treated as `RawText`. It seems we just need to replace `\\{{` with `{{` in `RawText`.

**Comment by softprops** [comment]
Would you be open to a pr if I can getting sooner than you? Context: I'm doing some prep work for a company hackathon by setting up some project templates with https://github.com/softprops/porteurbars which uses this lib as the underlying template engine. I ran into a problem with the escaped delimiter when I realized that one of these templates needed to emit {{foo}} in its output. The hackathon doesn't start until this thurs and friday but I wanted to try to get some prep work done early. Well also likely be using this tool for other companynproject templates in the future.

**Comment by sunng87** [comment]
Sure! Please make your PR for this. Thank you @softprops

**Comment by softprops** [comment]
Submitted hopefully a sane pr over here https://github.com/sunng87/handlebars-rust/pull/170

**Comment by sunng87** [comment]
Released in 0.28.2

**Comment by softprops** [comment]
Awesome thanks!
