### ISSUE TITLE
escape tag follow up

### ISSUE THREAD

**Issue by softprops** [sunng87/handlebars-rust#171]
After integrating the latest tag escaping changes with porteurbars I noticed something. a template in a separate file that contained `\\{{foo}}` was not technically what the current replace `\\{{` with `{{` does. `\` is an escape character in string literals in rust so this was more like replacing `\{{` with `{` leaving behind `\{{foo}}` which wasn't the intended effect. I wanted to report here. I can make a quick follow up pr but I wanted to open an issue for discussion if the pr ends up being the wrong impl so the conversation can live on.

**Comment by softprops** [comment]
I think this [playground link](https://play.rust-lang.org/?gist=6ef530cc02f2b45748c21e303f9ceae2&version=stable) describes it best

**Comment by sunng87** [comment]
Released in 0.28.3
