### ISSUE TITLE
Iterate through JSON Object that has keys with unusual characters

### ISSUE THREAD

**Issue by hucal** [sunng87/handlebars-rust#173]
Hello!
First off, thanks for all the great work!

I'm trying to render a Handlebars template that needs to iterate through a JSON object with keys that contain dots and spaces. This causes Handlebars to return a `RenderError` with description **`Invalid JSON path`**.

## Minimal Example

It fails in the same way if I replace `"strange key"` with `"strange.key"`. I tried this using handlebars-rust version 0.28.3.

```
extern crate handlebars;
#[macro_use]
extern crate serde_json;

use handlebars::Handlebars;

fn main() {
    Handlebars::new().template_render(
        "{{#each x}} {{@key}} {{this}}, {{/each}}",
        &json!({"x": {"a": 1, "b": 2, "strange key": 3}})
    ).map(|s| println!("{}", s)).unwrap();
}
```

## Handlebars Code

I believe this line in `src/grammar.rs` in today's master branch is relevant:

```
path_ident = _{ ['a'..'z']|['A'..'Z']|['0'..'9']|["_"]|["@"]|["$"]|["<"]|[">"]|["-"]}
```

I'm unfamiliar with Handlebars, but this grammar could be updated to support more general JSON keys, or it could be ignored if referring to the key using `this` or `@key`.

I'd be glad to submit a PR if necessary, but I would appreciate any help.

**Comment by sunng87** [comment]
Correct. Currently string with spaces is not treated as valid JSON `path`. 
I'll rethink about the `path_ident`, it seems we shouldn't have any restriction on the object key.

**Comment by hucal** [comment]
Thank you!
I think we can fix my issue without changing `path_ident`. The `each` helper shouldn't use the `path_ident` parser because the element will only be referred to using `@key` or `this`. I'd like to contribute to the project, so I'll look at the `{{#each}}` helper more closely soon.

I can make a separate issue for adjusting `path_ident`.

**Comment by sunng87** [comment]
Internally `#each` uses this path to find its local context (`this`) in the whole JSON object. I think we can fix this by adding support for `'p'`, `"p"` and `[p]` in path_ident. Then we will always use `[p]` for visiting JSON object.

**Comment by hucal** [comment]
I completely agree. I've been working a solution that only uses `[p]`. I have it working with this code:

```
extern crate handlebars;
#[macro_use]
extern crate serde_json;

fn main() {
    fn p<T: std::fmt::Debug>(s: T) {
        println!("{:?}", s);
    }

    handlebars::Handlebars::new().template_render(
        // BUG: odd keys and {{#each .}}
        "{{{nested.objects.[with very].[unusual.keys].[☺☻✌☹♡♥❤⚘❀❃❁✼☀✌♫♪]}}} \
         {{obj.[a]}} \
         {{obj/[abcdefg]}} \
         {{[obj].[strange key]}} \
         {{[obj]/[stranger key ! \" # % & ' ( ) * + , . / ; < = > @ \' / ..]}} \
         {{./obj.[stranger key ! \" # % & ' ( ) * + , . / ; < = > @ \' / .. } {{}} {]}} \
         {{obj.[ḫï]}} \
         {{obj.[ɦḝḷḷȯ ϵὑêґỳôпế!!]}} \
         {{obj.[☺☻✌☹♡♥❤⚘❀❃❁✼☀✌♫♪]}} \
         Objects: \
         {{#each obj}}`{{@key}}`: {{this}}, {{/each}}",
        &json!(
        { "obj": {
            "nested":{"objects": {"with very": {"unusual.keys": {"☺☻✌☹♡♥❤⚘❀❃❁✼☀✌♫♪": "♡♥❤<3"}}}},
            "a": 1,
            "abcdefg": 2,
            "strange key": 3,
            "stranger key ! \" # % & ' ( ) * + , . / ; < = > @ \' / ..": 4,
            "stranger key ! \" # % & ' ( ) * + , . / ; < = > @ \' / .. } {{}} {": 5,
            "ḫï": 6,
            "ɦḝḷḷȯ ϵὑêґỳôпế!!": 7,
            "☺☻✌☹♡♥❤⚘❀❃❁✼☀✌♫♪": 8
        }})
    ).map(p).map_err(p).unwrap_or_default()
}
```

I'd like a moment to clean up my solution, then I'll submit a pull request. 

It also fixes the other issue I created.

**Comment by sunng87** [comment]
@hucal Thank you! Remember to make your test code a test case in your pull request so we can track this feature in future.

**Comment by hucal** [comment]
I read this after submitting my pull request, I apologize. I'll submit an updated pull request with my test case.

Thank you for the great library!

**Comment by hucal** [comment]
Actually, I'd rather work on a few more test cases and on `helper_with.rs` before submitting another pull request.

**Comment by sunng87** [comment]
Nice, thank you @hucal

**Comment by hucal** [comment]
When you write,

> Then we will always use [p] for visiting JSON object.

Does this mean the tests on lines 305 and 311 in `src/context.rs` don't apply? They allow accessing property `q.p` by using `q.["p"]` or `q.['p']`. It seems my PR would override this part of the grammar.

**Comment by sunng87** [comment]
Just tested on handlebars.js

It seems the valid expression are:
`a/[b c]` or `a.[b c]`

for data
```
{
  a: { "b c": 1 }
}
```

None of `a.["b c"]`, `a["b c"]`, `a['b c']` will work. No additional quote is allowed in `[]`. I think we can align with handlebars and drop these legacy cases.
