### ISSUE TITLE
Can't access properties that are not valid identifiers

### ISSUE THREAD

**Issue by hucal** [sunng87/handlebars-rust#174]
It is impossible for a template to access a property that is not a valid identifier. For example, Handlebars-rust can't access any of the properties in the following JSON object:

```
{
  "key with spaces": 1,
  "key.with.dots": 0
}
```

**Comment by hucal** [comment]
## Proposed Solution

Handlebars.js uses the delimiters `"p"`, `'p'`, and `[p]` to allow access to properties with unusual names.

This is from the [Handlebars.js expressions manual](http://handlebarsjs.com/expressions.html):

> To reference a property that is not a valid identifier, you can use segment-literal notation, `[`:
...
> You may not include a closing ] in a path-literal, but all other characters are fair game.
JavaScript-style strings, " and ', may also be used vs. [ pairs.

**Comment by sunng87** [comment]
Yes, we need to support `"p"`, `'p'`, and `[p]` in path_ident. A little work needs to be done in pest grammar.

**Comment by sunng87** [comment]
Fixed in #176
