### ISSUE TITLE
@root support?

### ISSUE THREAD

**Issue by hammett** [sunng87/handlebars-rust#178]
Howdy, 
Is this something easy to add? https://stackoverflow.com/questions/17364897/access-to-root-context-in-handlebar-js-template

In essence, using ``@root`` from any depth should return a reference to the root RenderContext variables. 

Also, is it really necessary to clone the variables when invoking a partial? Cloning the map is causing some major performance issues here, it's taking ~5 min to run.

Thanks!

**Comment by sunng87** [comment]
Hi @hammett @root is not supported for now and I will definitely support it.

Currently I'm working on pest upgrade #177, which involves lots of changes so I will be working on this right after #177 is done.

For the second question I will look into it and come back to you this weekend.

**Comment by hammett** [comment]
Thanks @sunng87 I looked at the code, and thought that to implement both root and no clone, the RenderContext would have to have an Option<Rc<RenderContext>> back to the parent RC, but it touches way more than that, so I refrained from trying it for now.
