### ISSUE TITLE
Why does renderw take an &mut Write instead of using static dispatch?

### ISSUE THREAD

**Issue by quadrupleslap** [sunng87/handlebars-rust#190]
Also, I also don't know why `StringWriter` is needed.

**Comment by sunng87** [comment]
Because we want a generic API that can write to any target like file, string or TCP connection.

**Comment by quadrupleslap** [comment]
Currently the signature is:

```rust
pub fn renderw<T: Serialize>(
    &self, 
    name: &str, 
    data: &T, 
    writer: &mut Write
) -> Result<(), RenderError>;
```

But I'm wondering why it isn't:

```rust
pub fn renderw<T: Serialize, W: Write>(
    &self, 
    name: &str, 
    data: &T, 
    writer: W
) -> Result<(), RenderError>;
```

Which would be just as generic.

**Comment by lfairy** [comment]
Have you benchmarked it with static dispatch?

Handlebars is a pretty heavy library, and doesn't seem like the kind of thing that would benefit from monomorphization.

**Comment by quadrupleslap** [comment]
It's not the speed, it's just that I've never seen the use of trait objects as input parameters in idiomatic Rust, and using a type parameter would let you use the trait object version if you ever needed to, as well.

**Comment by sunng87** [comment]
@quadrupleslap I'm pretty open to this to make it idiomatic Rust. Could you please make a pull request for this? As we are preparing for the 0.30 and 1.0 release, a break change is OK for me.
