### ISSUE TITLE
Helper not defined: \"this\"" when using serde_json + handlebars-rust

### ISSUE THREAD

**Issue by ignatenkobrain** [sunng87/handlebars-rust#193]
```
ERROR: RenderError(RenderError { desc: "Helper not defined: \"this\"", template_name: None, line_no: None, column_no: None, cause: None })
```

Ref: https://github.com/Aaronepower/tokei/issues/157

**Comment by ignatenkobrain** [comment]
Relevant code:

```rust
fn generate_languages(out_dir: &OsStr) {
    let handlebars = {
        let mut h = Handlebars::new();
        h.register_escape_fn(handlebars::no_escape);
        h
    };

    let json: Value =  {
        let json = File::open(&"languages.json").expect("Cant open json");
        serde_json::from_reader(json).expect("Can't parse json")
    };

    let output = Path::new(&out_dir).join("language_type.rs");
    let mut source_template = File::open(&"src/language/language_type.hbs.rs")
        .expect("Can't find Template");
    let mut output_file = File::create(&output).expect("Can't create output");

    if let Err(err) = handlebars.template_renderw2(&mut source_template,
                                                   &json,
                                                   &mut output_file)
    {
        panic!("Failed to generate languages! ERROR: {:?}", err);
    }
}
```

**Comment by ignatenkobrain** [comment]
This worked fine with 0.28, but not with 0.29.. I have very small amount of knowledge about handlebars, so help is highly appreciated.

**Comment by sunng87** [comment]
hi @ignatenkobrain , from the code I didn't see a helper named `this` registered. Could you please show me the template? `src/language/language_type.hbs.rs`

**Comment by sunng87** [comment]
Found in your repo. I will look into this issue.

**Comment by sunng87** [comment]
@ignatenkobrain it's a parser issue. 0.29 handlebars has updated the JSON path expression parser. Please change [your template line 250](https://github.com/Aaronepower/tokei/blob/master/src/language/language_type.hbs.rs#L250) to `{{this.extensions.[0]}}` and I think it will work.

**Comment by ignatenkobrain** [comment]
@sunng87 cool! thanks a lot! do you think it would be possible to print line where it is happening? it was not obvious to find for me.

**Comment by sunng87** [comment]
At the moment, `template_renderw2` won't generate template mapping. I will change this behaviour in 0.30
