### ISSUE TITLE
Require `Sync` for `cause` of `RenderError`

### ISSUE THREAD

**Issue by lo48576** [sunng87/handlebars-rust#194]
Rust's std library provides type conversions for `Box<Error>` and `Box<Error + Send + Sync>`, but not for `Box<Error + Send>`.
So, definition of `cause: Option<Box<Error + Send>>` (without `Sync` bound) in `RenderError` decreases interoperability between various error types.
For example:

* [`std::io::Error` requires the cause to be `Error + Sync + Send`](https://doc.rust-lang.org/std/io/struct.Error.html#method.new) and `RenderError` cannot be used.
* [`std::boxed::Box` implements `From` and `Into` conversions for `Box<Error>` and `Box<Error + Send + Sync>`](https://doc.rust-lang.org/std/boxed/struct.Box.html#implementations), but not for `Box<Error + Send>`.

These problems will be solved if `cause: Option<Box<Error + Send + Sync>>`.

Is there any reason why the `cause` doesn't require `Sync`?

**Comment by sunng87** [comment]
This is not designed. I will add `Sync` for `cause`

**Comment by sunng87** [comment]
Released in 0.30.0-beta4

**Comment by steveklabnik** [comment]
I'd love to see this get released! That makes this crate work seamlessly with `Failure`.

**Comment by sunng87** [comment]
I'll release this once pest 1.0 stable is out.

**Comment by steveklabnik** [comment]
Seems good 👍
