### ISSUE TITLE
Docs badge is invalid.

### ISSUE THREAD

**Issue by thelearnerofcode** [sunng87/handlebars-rust#198]
The badge points to [https://docs.rs/handlebars/](https://docs.rs/handlebars/), but that 404s. ("The requested resource does not exist")

**Comment by sunng87** [comment]
oh, seems docs.rs has changed their url pattern. I will fix this later today.

**Comment by sunng87** [comment]
Fixed in a17d5bc . Currently docs.rs's rustc is a little dated and it has trouble building pest, the parser library we use. So the docs isn't up to date at the moment.
