### ISSUE TITLE
any chance of `Handlebars` implementing `Debug`?

### ISSUE THREAD

**Issue by steveklabnik** [sunng87/handlebars-rust#199]
I'd like to put an instance of `Handlebars` in a struct that implements `Debug`. Would you be interested in taking a patch that adds this impl? It's generally considered a good practice for all public types to implement: https://rust-lang-nursery.github.io/api-guidelines/debuggability.html#all-public-types-implement-debug-c-debug

Thanks!

**Comment by sunng87** [comment]
No problem @steveklabnik , I will add Debug to all public types, later.

**Comment by sunng87** [comment]
Implemented in 0.30.1

**Comment by steveklabnik** [comment]
Oh thank you! Quite fast 😄
