### ISSUE TITLE
A problem with regex_macros

### ISSUE THREAD

**Issue by freiguy1** [sunng87/handlebars-rust#2]
At runtime, I'm getting an error:

`error while loading shared libraries: libregex_macros-[...].so`

after adding a reference to this library.  After asking about this on irc, burntsushi said 

> you need to use `#[no_link] #[plugin] extern crate regex_macros;`

He then added why:

 > the reason why you need all this special stuff is because `regex!` is a compiler plugin and not just a normal macro. in fact, it won't work in the stable channel of Rust 1.0!

Could you fix this or get back to me on how I can continue on without it? Thanks!

**Comment by sunng87** [comment]
Thanks for the information and patch.
