### ISSUE TITLE
How can I get error when some field is missing in the data model?

### ISSUE THREAD

**Issue by pftbest** [sunng87/handlebars-rust#203]
I want to get an error message when I forgot to add some field in my data struct.

Example code:
```Rust
extern crate handlebars;
extern crate serde;
#[macro_use(Serialize)]
extern crate serde_derive;

static TEMPLATE: &str = r#"
int hello_{{name}}(int &value)
{{~#if need_body}} {
    return 0;
}{{~else}};
{{~/if}}
"#;

#[derive(Serialize)]
struct Data {
//    name: String,
    need_body: bool,
}

fn main() {
    let data = Data {
//        name: "some_name".into(),
        need_body: true,
    };
    let reg = handlebars::Handlebars::new();
    let out = reg.render_template(TEMPLATE, &data).unwrap();
    println!("{}", out);
}
```

**Comment by sunng87** [comment]
You will need a helper like this (not tested, may contains error):

```rust
use handlebars::*;
use serde_json::value::Value;
handlebars.register_helper("strict", |h: &Helper, _: &Registry, rc: &mut RenderContext| -> HelperResult {
    let v = h.param(0).map(|v| v.value()).ok_or(RenderError::new("param not found"))?;
    if v == Value::Null {
        return Err(RenderError::new("param cannot be null"));
    }

    rc.writer.write(v.render().into_bytes().as_ref())?;
    Ok(())
})
```

**Comment by pftbest** [comment]
So there is no way to enable such behavior globally? Using a helper everywhere in the code will be very inconvenient.

**Comment by sunng87** [comment]
The handlebars language was based on JavaScript, it renders empty string for this situation.

I think I can add a strict switch on handlebars registry to control this behaviour.

**Comment by pftbest** [comment]
That would be great, thank you!

**Comment by sunng87** [comment]
@pftbest the feature impl is almost ready in #204. Could you please use this branch and verify if it works for your case?

**Comment by pftbest** [comment]
@sunng87 It works great, thank you! I was a bit worried that it might handle `Option<String>` different, but it did just fine.

**Comment by sunng87** [comment]
Nice! Thank you @pftbest , a new release is coming.
