### ISSUE TITLE
Json lifetime issue causing too many clones

### ISSUE THREAD

**Issue by sunng87** [sunng87/handlebars-rust#206]
Currently we have received report that handlebars-rust doesn't scale well on large dataset (#195) . The reason is we have too many clones in helper render. 

In handlebars render process, we have value from several different sources, which have their own lifetime individually. In order to provide values for helper API, currently we use `clone` to bypass the lifetime issue. Of course, it is quite expensive.

The different sources of value include:

* JSON constants: the constants value defined in template, for example `{{some-helper 1 true "abc"}}`, where `1`, `true` and `"abc"` are constants hard-coded into template, and we hold these data in a lifetime of `Template`.
* Value from render call. This is the most typical source. When you call render you have to provide some data. And the value given to helper is just a reference of part of you data. For example, in `{{some-helper a.b}}` we will seek value for JSON path `a.b` and clone the value for helper use. Note that the value of `a.b` has same lifetime with the context data, which is scoped in render call.
* Value computed from subexpression. Subexpression is a tricky feature that use the render result of expression as helper param, or even helper name. For instance, `{{some-helper (another-helper a.b)}}`, the value provided for `some-helper` is the result of `another-helper` call. And in this case, the lifetime of its result is limited to the helper invocation if we don't clone it.

So to remove clones as much as possible, I think we can:

* Design a new helper API that doesn't own JSON value at all time
* Have finer granularity on JSON value lifetime, use a API like `std::borrow::Cow` that support different lifetime

This may cause helper API change so I suggest to implement this before 1.0 release (as we already have break change #200 that planned for 1.0)

**Comment by dginev** [comment]
:+1: from me, I would love to use handlebars for rendering my 3,300 row HTML table (~ 2 MB of HTML).

**Comment by sunng87** [comment]
Fixed in #224
