### ISSUE TITLE
Register template folder

### ISSUE THREAD

**Issue by sunng87** [sunng87/handlebars-rust#207]
Provide a handy method on `Registry` that register all templates in a folder.

This is already implemented in [handlebars-iron](https://github.com/sunng87/handlebars-iron/blob/master/src/sources/directory.rs) as `DirectorySource` . We just need port it into handlebars and deal with error properly.

**Comment by gamebox** [comment]
I'm a new Rust developer, but would like to tackle this.

**Comment by sunng87** [comment]
@gamebox Thanks! You are welcomed to join and work on this. Please create a branch from master. 

Let me know if you have any question with this feature.

**Comment by gamebox** [comment]
One thing I want to clarify: When we register a directory, is the assumption that we want to use the filename (minus the extension) as the name for the template?

**Comment by sunng87** [comment]
@gamebox Yes. By register folder we assume the relative path name is the template name. In handlebars-iron you will specify path prefix(template root path) and suffix(template file extension), the path between prefix and suffix and treated as template name

**Comment by gamebox** [comment]
Cool, I actually got the answer myself by reading the source in `handlebars-iron`.  Now I have a _working_ implementation(verified in the render-cli example), the only thing left to be decided is error behavior.  Do we want to bail if any file fails to load?  Or only if it cannot render?

**Comment by sunng87** [comment]
I think we should return an error on that case. But that may leaves some of templates registered in Registry. It would be great if we can "rollback" when error occurs.

**Comment by gamebox** [comment]
For those tracking this, my PR is in review. #223

**Comment by sunng87** [comment]
Implemented in #223
