### ISSUE TITLE
Build fails on latest nightly

### ISSUE THREAD

**Issue by torkleyy** [sunng87/handlebars-rust#209]
Not sure if it's `pest_derive` or this crate, but the build fails on the latest nightly (`2018-03-29`):

https://travis-ci.org/slide-rs/specs/jobs/360451251#L749

```
error[E0518]: attribute should be applied to function
 --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/handlebars-0.31.0/src/grammar.rs:3:10
  |
3 | #[derive(Parser)]
  |          ^^^^^^ not a function
error: aborting due to previous error
For more information about this error, try `rustc --explain E0518`.
error: Could not compile `handlebars`.
```

**Comment by sunng87** [comment]
Thanks for reporting. I can reproduce it with latest rustc. It seems to be a break change for macro system. 

https://github.com/pest-parser/pest/issues/218 is tracking this.

**Comment by sunng87** [comment]
This is fixed in latest pest. `cargo update` should help.

**Comment by jaroslaw-weber** [comment]
my Travis builds are failing because of this.
I'm using `handlebars = "0.32.0"`, and `cargo update` is not changing a version.

What would be the workflow for this? Do I need to manually update version of handlebars in all of my crates depending on handlebars to the new 1.0-beta version of hb?

**Comment by sunng87** [comment]
hi @jaroslaw-weber , running `cargo update` should update `pest` to 1.0.7. And if your project is an app, you'd better add `Cargo.lock` to source management. 

This update has nothing to do with 1.0-beta.
