### ISSUE TITLE
Access TemplateElement enum

### ISSUE THREAD

**Issue by mutlusun** [sunng87/handlebars-rust#210]
Hello,
thanks for your awesome project!

I am trying to write a small CLI tool for managing LaTeX templates with dynamic expression replacement. So I want handlebars to scan a template file for expressions and then ask the user how to replace them. For example `{{title}}` could be `A LaTeX document` and on another day it could be `Another LaTeX document`. Somehow I need access to the found expressions in a template and ask the user for replacements.

I tried `reg.get_template("tmp").unwrap().elements`. On this way I get all the elements, but I cannot check them against `TemplateElement::RawString` for example. If I want to use this enum, I get the following error:
```{rust}
extern crate handlebars;

fn main() {
    let test = handlebars::Template::TemplateElement::RawString(String::from("test"));
}
```
```
error[E0223]: ambiguous associated type
 --> src/main.rs:4:16
  |
4 |     let test = handlebars::Template::TemplateElement::RawString(String::from("test"));
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ambiguous associated type
  |
  = note: specify the type using the syntax `<handlebars::Template as Trait>::TemplateElement`

error: aborting due to previous error
```

But if I change the code as suggested, it won't work either. You know what I miss? Is there an easier way to achieve my goal? Or is this enum not intended to be addressed from an outside crate?

I'm sorry that this is more of a programming question than a bug report. But I would appreciate it, if you could help me.

**Comment by sunng87** [comment]
The `TemplateElement` is for internal use only. 

Based on you case, I suggest you to write a helper, say `prompt`. When rendering `{{prompt title}}`, it asks user to type something.

**Comment by mutlusun** [comment]
Hello @sunng87 ,
thanks for your help and sorry for my late reply!

Now I have seen in the docs that I can even build conditional helpers. This is perfect for my use case!

Best
mutlusun
