### ISSUE TITLE
Comments are present in the output

### ISSUE THREAD

**Issue by jonathanmorley** [sunng87/handlebars-rust#214]
According to https://handlebarsjs.com/#comments the following handlebars template should have no content:

```
{{! Comment}}
```

However, with handlebars-rust we get the following:

```
<!-- Comment-->
```

This can cause issues if the template is not XML-based

**Comment by jonathanmorley** [comment]
I think that might be a misreading of the JS docs.

It looks like it is recommending to use `<!-- Comment -->` if you want the comment to show up in the output.

```
{{!-- comment --}}
```

Is just to allow `{{` and `}}` within the comment block

**Comment by sunng87** [comment]
@jonathanmorley there is section on handlebarsjs.com for this.

https://handlebarsjs.com/#comments

**Comment by sunng87** [comment]
Just verified from tryhandlebarsjs.com @joerixaop @jonathanmorley you are right. I will release a fix later today.

**Comment by sunng87** [comment]
released in 0.32.2
