### ISSUE TITLE
handlebars 0.32.3 breaks compatibility

### ISSUE THREAD

**Issue by KeenS** [sunng87/handlebars-rust#218]
Because it has started to [use `impl Trait`](https://github.com/sunng87/handlebars-rust/blob/master/src/template.rs#L146), it breaks compatibility under rustc < 1.26.0, which should not occur in non-major update.
I suggest to [yank](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-yank) 0.32.3 and re-release it as 0.33.0.

**Comment by sunng87** [comment]
Thanks for reporting. I will switch to generics as `impl Trait` are all on parameter types.

**Comment by sunng87** [comment]
0.32.4 released for this.

**Comment by KeenS** [comment]
Thank you for your quick fix.
