### ISSUE TITLE
Expose Template Elements

### ISSUE THREAD

**Issue by rflaperuta** [sunng87/handlebars-rust#225]
I'm devising a helper that calls an API, the API individual calls are metered.

I though it would be nice to scan the template returned by `get_template`, iterate and accumulate all related helper usage, and call the API once, passing all the parameters using this helper. (This batch API call can optimize speed and escape metering to an extent)

My dificulty starts with not being able to iterate via match on the Vec<TemplateElement>, is it possible to expose it and its sibblings publicly on the API?

**Comment by sunng87** [comment]
No problem. I just made template mod public, please check if the master branch work for you.

Also could you please show me your helper implementation? I'd like to see if anything I can do to improve the helper API for your case.

**Comment by rflaperuta** [comment]
Just tested and now I can access all elements that I need.

The helper isnt finished yet, but you can take a look at the progress in:
https://github.com/rflaperuta/ssm_helper

I suppose it will convey the needs better than explaining it here...

**Comment by sunng87** [comment]
Nice. I think you were using the API for debug purpose right? It looks good to me. Thanks!
