### ISSUE TITLE
Doesn't allow dynamic partials

### ISSUE THREAD

**Issue by sitnin** [sunng87/handlebars-rust#23]
Handlebars has a "dynamically named partials". It looks like ```{{> (partialTplName) }}```

```partialTplName``` is a context variable which hbs should interpolate and use proper partial.

I took handlebars-iron's example, extracted partial and passed it's name to the Template's context. If I use partial's filename directly or just printing partialTplName with ```{{partialTplName}}``` it looks like expected. If I trying to use DNP, template outputs zero characters without any errors.

**Comment by sunng87** [comment]
Yes, the `{{> (...)}}` expression is not supported by handlebar-rust currently. I will find some time to add this feature.

**Comment by sitnin** [comment]
It would be great! :)

**Comment by sunng87** [comment]
@sitnin This should be supported now. Please `cargo update` and check if it works for you.
