### ISSUE TITLE
pest 2.x

### ISSUE THREAD

**Issue by ignatenkobrain** [sunng87/handlebars-rust#237]
Would be cool if you could switch to new pest which was released not so long time ago ;)

**Comment by sunng87** [comment]
Cool! Didn't noticed the version were released. It's definitely on my TODO. I will start to work on it when I'm back from vocation.

**Comment by sunng87** [comment]
Currently upgrade is blocked by a request for accessing line/column number from `Error`.
https://github.com/pest-parser/pest/issues/307

**Comment by sunng87** [comment]
Handlebars with Pest 2.0 is ready to merge (#242 ) except it will break support for Rust 1.23, which is required by [Criterion](https://github.com/japaric/criterion.rs). 

I am going to release this as handlebars 2.0 and drop support for earlier versions of Rust.

**Comment by ignatenkobrain** [comment]
Could you release new version of handlebars?
