### ISSUE TITLE
register_templates_directory includes a period

### ISSUE THREAD

**Issue by steveklabnik** [sunng87/handlebars-rust#238]
I have a basic application that does this:

```rust

       handlebars.register_templates_directory("hbs", "templates").expect("Couldn't find templates directory");

// later...

  let response = self.handlebars.render("hello.", &data).unwrap();

```

This would panic, with output like this:

```text
Template not found: hello
```

I decided to add a short loop right after the `register_templates_directory` call:

```rust
        for (name, _) in handlebars.get_templates() {
            println!("found template: {}", name);
        }

```

and it printed this:

```text
found template: hello.
```

Note the extra `.`. If I change my render call to be

```rust
            let response = self.handlebars.render("hello.", &data).unwrap();
```

it now works. This feels like a bug!

**Comment by sunng87** [comment]
hi @steveklabnik . May I know you handlebars version?

I cannot reproduce this issue in master. Also from your code you are rendering `hello.`

```rust
let response = self.handlebars.render("hello.", &data).unwrap();
```

But the error report says `hello`:

```
Template not found: hello
```

Could you please confirm ?

**Comment by steveklabnik** [comment]
I was using 1.0.5. However, I cannot reproduce now either; I must have had something wrong on my side somewhere. Sorry for the noise!

**Comment by sunng87** [comment]
Never mind. Feel free to ask any question during handlebars development.
