### ISSUE TITLE
includeZero flag is missing

### ISSUE THREAD

**Issue by mraof** [sunng87/handlebars-rust#240]
This code
```handlebars
{{#if previous includeZero=true}}
```
should treat `previous` as true when `previous` is `Some(0)` because of the includeZero flag.
The way around this currently is to use an `Option<String>` instead of an `Option<i32>`

https://github.com/wycats/handlebars.js/issues/608 Relevant handlebars.js issue

**Comment by sunng87** [comment]
Thanks! Didn't know the option on `if` helper, this will be supported soon.
