### ISSUE TITLE
Problem writing a custom boolean helper

### ISSUE THREAD

**Issue by Keruspe** [sunng87/handlebars-rust#241]
Hi,

I'm trying to write a custom boolean helper and I'm hitting a behaviour I don't understand.
I'm not using the handlebars_helper macro because I'm using some complex structure as input, not just a number or such.

Here is a minimal reproducer of my problem, this version works, but if I drop the `out.write` line from the helper and use the one from below instead, it doesn't work. This seems to be what's done by the handlebars_helper macro though, unless i'm missing some point.
Why do I have to do this trick and why doesn't the commented line work as expected?

```
extern crate handlebars;
extern crate serde;
#[macro_use] extern crate serde_derive;

use handlebars::*;

fn foobar_helper(h: &Helper, _: &Handlebars, _: &Context, _: &mut RenderContext, out: &mut Output) -> HelperResult {
    let ok = 42 == h.param(0).unwrap().value().as_u64().unwrap();
    out.write(if ok { "true" } else { "" })?;
//    out.write(ok.to_string().as_ref())?;
    Ok(())
}

#[derive(Serialize, Deserialize)]
struct Foo;

fn main() {
    let mut h = Handlebars::new();
    h.register_helper("foobar", Box::new(foobar_helper));
    h.register_template_string("template", "{{#if (foobar 1)}}Ok{{else}}Not ok{{/if}}").unwrap();
    println!("{}", h.render("template", &Foo).unwrap());
}
```

**Comment by sunng87** [comment]
Hi @Keruspe, when using helper in subexpression, the output is treated as json string, so any non-empty value is considered as true. 

If your helper is mainly used for subexpression, I suggest you to implement the [the typed helper function, `call_inner`](https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/mod.rs#L77) (the one used by `handlebars_helper!` macro). 

A code sample is like:

```rust
struct MyHelper;

impl Helper for MyHelper {
    fn call_inner<'reg: 'rc, 'rc>(
        &self,
        h: &Helper<'reg, 'rc>,
        _: &'reg Registry,
        _: &'rc Context,
        _: &mut RenderContext<'reg>,
    ) -> Result<Option<ScopedJson<'reg, 'rc>>, RenderError> {
        Ok(Some(ScopedJson::Derived(json!(42 == h.param(0).unwrap().value().as_u64().unwrap()))))
    }
}
```

**Comment by Keruspe** [comment]
Thanks for the clarification
