### ISSUE TITLE
Array access expressions fails: invalid digit found in string

### ISSUE THREAD

**Issue by RalfJung** [sunng87/handlebars-rust#246]
With handlebars 0.28.3, I used `{{this[0].field}}` to access a field of the first element of an array in a loop iteration. Since the upgrade to handlebars 1.1.0, this fails, saying `invalid digit found in string`.  Using just `{{this[0]}}` says `Helper not defined: "this"`.  With `{{this}}`, it renders `[[object], [object], ]`, showing that indeed I have an array.

So far, I found no way to access elements of an array it handlebars 1.1.0.  None of the examples does this, but the changelog also does not indicate that anything should have happened here.

**Comment by sunng87** [comment]
there was a json path visitor revamp after 0.28, the array access expression has been aligned with handlebarsjs. Now you should be able to use `{{this.[0].field}}` for the `field` of array's first element.

**Comment by RalfJung** [comment]
Thanks, that works!

As someone slightly familiar with JS and not at all familiar with handlebars, this is really surprising.  Not sure if it is possible to at least give better diagnostics in this case?

**Comment by sunng87** [comment]
Good suggestion. Neither handlebars-rust nor the original javascript version has detailed documentation about the expression, which is slightly different from what we general thought to be. So in earlier versions I made a mistake on the implementation.

I think it's better to add meaningful error messages or warnings when such expression detected.
