### ISSUE TITLE
No way to query if a variable exists in strict mode

### ISSUE THREAD

**Issue by iirelu** [sunng87/handlebars-rust#247]
Leaving strict mode on all the time worked well for me until now. I want to do something simple, like change the page's title if the variable "title" is set, but I can't do that because `{{#if title}}` throws up an error when title isn't defined. This is pretty counterintuitive, there should probably be an exception to the strict rules for if/unless blocks, or at least a helper that could be used like `{{#if (exists title)}}`.

**Comment by sunng87** [comment]
So I think a better approach for strict mode is to restrict access on `{{title}}` only and allow subexpression/helper access.

**Comment by sqwishy** [comment]
Personally, I find new behaviour very surprising. Having a helper that maps an error to a null/undefined as originally proposed seemed like a really sensible idea. At the very least, it would have been nice if the documentation made it clear that strict mode isn't enforced reliably.
