### ISSUE TITLE
stripping lines that are "standalone" helpers

### ISSUE THREAD

**Issue by robinvd** [sunng87/handlebars-rust#258]
In the handlebars.js docs the following is described (https://handlebarsjs.com/expressions.html):
```
This expands the default behavior of stripping lines that are "standalone" helpers (only a block helper, comment, or partial and whitespace).
```
They give the example:
```
{{#each nav}}
  <a href="{{url}}">
    {{#if test}}
      {{title}}
    {{^}}
      Empty
    {{/if}}
  </a>
{{~/each}}
```
That will render as
```
<a href="foo">
    bar
</a>
<a href="bar">
    Empty
</a>
```

Thus rendering the line `{{#if test}}` as nothing. Currenly on handlebars.rs:
```
----------
{{#if body}}
{{ body }}
{{/if}}
```
renders as
```
----------

body here
```
(notice the newline between '---' and 'body here'.) Is it possible to ignore those lines?

**Comment by sunng87** [comment]
Good catch. This is what we should support.

**Comment by zuobaoquan** [comment]
Any plan on this? It is very annoying, especially when generating code.
P.S. Partial templates should be supported either.

**Comment by sunng87** [comment]
This is blocked by an issue with pest parser. I'm waiting for pest 3.0 to see if it will be resolved.

**Comment by zuobaoquan** [comment]
> This is blocked by an issue with pest parser. I'm waiting for pest 3.0 to see if it will be resolved.

Any issue reference? or could you create the issue on that repository? Thanks

**Comment by sunng87** [comment]
IIRC this was the issue:

https://github.com/pest-parser/pest/issues/396

**Comment by shawntabrizi** [comment]
+1 for running into this issue

**Comment by sunng87** [comment]
I'm adding `helper wanted` label for this so anyone interested in could pick this up. I can offer help as much as I can.

**Comment by SuperCuber** [comment]
Currently, in my usage of handlebars, I use the rule of thumb of appending `~` to every part of conditional syntax.
For example:
```
-----
{{#if body~}}
{{body}}
{{else~}}
No body
{{/if~}}
More text
```
Will render as either
```
-----
Body here
More text
```
Or
```
-----
No Body
More Text
```

If I do want an empty line after the if-else block, I put it in both branches, and this of course works with no `else` block as well.

**Comment by shawntabrizi** [comment]
Yeah I was able to work around this too by actually prepending `~` everywhere:

https://github.com/paritytech/substrate/pull/7447/files

None the less, I still believe (although not 100% sure now) that the handlebars rendering by default would not need such stuff.
