### ISSUE TITLE
Block parameters can't be used as context for partials

### ISSUE THREAD

**Issue by thegedge** [sunng87/handlebars-rust#260]
This test case fails:

```rust
#[test]
fn test_partial_with_blocks() {
    let hbs = Handlebars::new();

    let data = json!({
        "a": [
            {"b": 1},
            {"b": 2},
        ],
    });

    let template = "{{#*inline \"test\"}}{{b}};{{/inline}}{{#each a as |z|}}{{> test z}}{{/each}}";
    assert_eq!(
        hbs.render_template(template, &data).unwrap(),
        "1;2;"
    );
}
```

I've verified on http://tryhandlebarsjs.com/ that this is the right output.

**Comment by thegedge** [comment]
This is impacting me right now on 2.0.0-beta.2. I'd be happy to pick up the work, but I wanted to first log it as an issue :)

**Comment by sunng87** [comment]
Thanks! If it works on handlebars.js, it's something we expected to support. 

The context issue is usually quite complex. I'm here to offer help if you need.

**Comment by sunng87** [comment]
The issue is how I visit context value here: 

https://github.com/sunng87/handlebars-rust/blob/master/src/partial.rs#L22

I'm using the local variable name to concat with current path root, for the json path. And here `z` is a local alias so it won't work. This may require a re-implementation of block context through handlebars-rust. Do you have any progress on this? Otherwise I will take on this and start the re-implementation.

**Comment by thegedge** [comment]
No progress, @sunng87. I usually only find a few hours on the weekend, so progress would likely be slow. You have more context here, so if you're interested in taking on the effort, go ahead (and thanks!)

**Comment by thegedge** [comment]
Possibly related:

```rust
#[test]
fn test_each_with_block_parameter() {
    let hbs = Handlebars::new();

    let data = json!({
        "a": [
            [1, 2, 3],
            [1, 4, 9],
        ],
        "b": 3,
    });

    let template = "{{#each a as |z|}}{{#each z}}{{.}},{{/each}}{{/each}}";
    assert_eq!(
        hbs.render_template(template, &data).unwrap(),
        "1,2,3,1,4,9,"
    );
}
```

```
failures:

---- test_root_with_blocks stdout ----
thread 'test_root_with_blocks' panicked at 'assertion failed: `(left == right)`
  left: `"[object],[object],[object],[object],[object],[object],"`,
 right: `"1,2,3,1,4,9,"`', tests/root_var.rs:36:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
