### ISSUE TITLE
How do i call a member function of impl of a struct in rust from hbs file?

### ISSUE THREAD

**Issue by surajpayu** [sunng87/handlebars-rust#262]
For example
Lets say i have simple struct

```
pub struct EventLogger{
     id: String,
}

impl EventLogger{
    pub fn raise_event(&self, id: String)->String{
        "hello".to_string()
    }
}
```

Is it possible to call raise_event from hbs file?  Any example to understand it?

**Comment by sunng87** [comment]
You can impl `HelperDef` trait for `EventLogger` and in the `call` function, you actually call `raise_event`.

An example can be found here: https://github.com/sunng87/handlebars-rust/blob/master/src/lib.rs#L243

**Comment by surajpayu** [comment]
Ok I will try that. Thanks for the information.
