### ISSUE TITLE
Infer the schema of the data required to render a given template.

### ISSUE THREAD

**Issue by snawaz** [sunng87/handlebars-rust#268]
Handlebars is awesome. We're using it to generate services and mock services from service-model. However, generating code interactively requires a feature which seems to be missing in the library. In short, it'd be great to have a feature like the following:

```rust
// template for protobuf definitions
let template = r#"
    import "{{service_name}}_data_model.proto";
    package {{service_name}}.stub_models;

    {{#each methods ~}}
    message {{this.proto_name}}Stub {
        {{this.input_proto_type}} request = 1;
        {{this.output_proto_type}} response = 2;
    }
    {{/each}}
"#

let mut reg = Handlebars::new();
let schema = reg.infer_schema(template)?;  # missing feature!
println!("schema: {:#?}", schema); 
```

Output: 

```JavaScript
{
   "service_name" :  "string",
   "methods" : [{
         "proto_name" : "string",
         "input_proto_type" : "string",
         "output_proto_type" : "string"
    }],
}
```
which can be interpreted as: the schema that is required to render the given `template`, must be a `map` with (at least) two keys:
   - `service_name` .. whose value is a string.
   - `methods` .. whose value must be an `array of map` with (at least) 3 keys:
      - `proto_name` .. whose value is a string
      - `input_proto_type` .. whose value is a string
      - `output_proto_type` .. whose value is a string

If we have such a feature, then a rendering engine can be written in such a way that it'll take _any_ template from users (e.g a template-file on command-line) and then the engine will infer the schema  and then asks users to enter the values for each key/field in the schema (recursively).

_(I'd be happy to implement this if the idea seems interesting and useful. It's going to be pretty challenging though.)_

**Comment by sunng87** [comment]
Sounds interesting. I understand your need is to extract the minimal required data structure for rendering a given template.  This probably can be done in a library, by analysing handlebars' `Template` data structure. It's provided through `getTemplate` from `Handlebars` and you can iterate over its `elements` for data you are instrested in. 

However, for data types, the handlebars template language was originally created for JavaScript, which is dynamic typed language. It's almost impossible to tell the data type from template.

**Comment by sunng87** [comment]
I can offer help if you need for understanding the template data structure.

**Comment by snawaz** [comment]
> Sounds interesting. I understand your need is to extract the minimal required data structure for rendering a given template. 

Yes. Exactly. 

> This probably can be done in a library, by analysing handlebars' `Template` data structure. It's provided through `getTemplate` from `Handlebars` and you can iterate over its `elements` for data you are instrested in.
> 

Looks like you're referring to this struct: https://docs.rs/handlebars/2.0.0-beta.2/handlebars/template/struct.Template.html

I'll have a look at it. Maybe, using this, we can implement this feature. 

> However, for data types, the handlebars template language was originally created for JavaScript, which is dynamic typed language. It's almost impossible to tell the data type from template.

I dont think it is impossible. We might not be able to distinguish between `string` and `number`, as in the template, we dont do anything number-specific, or string-specific. However, if we use `{{#each methods}}  ... {{/each}}`, then it implies that `methods` must be a collection of _things_. It could be a `array`, `vector`, `set`, etc. So assuming it to be an array/vector is safe.

**Comment by snawaz** [comment]
> I can offer help if you need for understanding the template data structure.

Thanks for the offer. I'll surely ask you if I'm stuck or need help. I'll first go through the doc and code, will try to understand myself. :-)

**Comment by sunng87** [comment]
Close for inactive.
