### ISSUE TITLE
Unable to iterate over helper output

### ISSUE THREAD

**Issue by tones111** [sunng87/handlebars-rust#270]
I'd like to write a helper that can output a list to be iterated by each.

example:
{{#each (values_helper values)}}
value: {{.}}
{{/each}}

where values is a vec and values_helper does some non-trivial operations like sorting and removing duplicates.

This seems to be currently not possible because the renderer's call_helper_for_value always puts the helper's output into a json string which the each helper complains is not iterable.

Maybe this will become possible with #252?

**Comment by sunng87** [comment]
You can define your helper to implement `call_inner`, that returns an `ScopedJson` for this case, and return a JSON instead of writing into `output`. 

If needed, I can add a test case to demo its usage later today.

**Comment by tones111** [comment]
Thanks for the tip.  I was able to implement the functionality I was looking for!

**Comment by sunng87** [comment]
Nice! Let me know if you have any question with handlebars.
