### ISSUE TITLE
Support for partial context/parameters

### ISSUE THREAD

**Issue by SkylerLipthay** [sunng87/handlebars-rust#28]
[Partial context](http://handlebarsjs.com/partials.html#partial-context) and [partial parameters](http://handlebarsjs.com/partials.html#partial-parameters) seem to be unsupported by `IncludeHelper`. How much work would it take to implement these features? With some direction, I would be happy to contribute.

**Comment by sunng87** [comment]
Thanks for reporting. 

In order to support partial context and partial parameters, we need to get informations from `IncludeHelper`'s parameter and hash, and update the context `c` we use to [render](https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/helper_partial.rs#L27).

**Comment by sunng87** [comment]
If you are going to take this feature, please kindly let me know. Otherwise I will start to work on it this weekend. :smiley:

**Comment by SkylerLipthay** [comment]
Thanks for the help!

I tried to implement partial contexts with SkylerLipthay/handlebars-rust@e615afe. The test passes, but only if you provide a path as the context parameter. Apparently the official handlebars.js supports passing string values as context as well, but I'm not sure how to best support this.

**Comment by sunng87** [comment]
@SkylerLipthay currently handlebars-rust doesn't support (at least not tested) string values as context. 
Could you please make a PR with current code? And I will look into what to change in feature.

Thanks!

**Comment by sunng87** [comment]
@SkylerLipthay is it OK for me to cherry-pick your commit into my feature branch?  I'm planning to work on this.

**Comment by SkylerLipthay** [comment]
My apologies! I did not get your prior message until just now. Please feel free to accept the PR or cherrypick the commit, whatever is easier.

Thank you for working on this.

**Comment by sunng87** [comment]
Never mind! Thanks for the PR. I will merge it into mainline.
