### ISSUE TITLE
Attach custom data to Helper.

### ISSUE THREAD

**Issue by jagt** [sunng87/handlebars-rust#281]
Hi!

I'm new to both rust and handlebar-rust, so I'm not quite sure if this is even possible.
Say I want to create a helper that references something else:

```rust
pub struct FooHelper<'a> {
    foo: &'a Foo,
}

let foo = Foo{}
handlebars.register_helper("foo_helper", Box::new(FooHelper{foo: &foo}));
```

This won't work as `register_helper` needs the helper to have `'static` lifetime. Does this mean that I can not attach a reference to the helper? Or maybe this is how it is intended to avoid some behaviors?

Thanks in advance!

**Comment by sunng87** [comment]
Yes, the `'static` lifetime we were using doesn't allow borrowed runtime data in helper. I will look into if it's possible to use a proper lifetime for this case. Ideally we should be able to use borrowed data with lifetime equals to the registry.

**Comment by sunng87** [comment]
@jagt could you please check the case in #282 if it works for you
