### ISSUE TITLE
Function for accessing template variables

### ISSUE THREAD

**Issue by Nukesor** [sunng87/handlebars-rust#291]
Hey!

I'm currently trying to build a mechanism, which allows to dynamically parse templates and furthermore accepts arbitrary parameters with arbitrary names.

My goal is to get a list of all parameters in the template and check whether these are satisified by the incoming parameters.

E.g. `"This is a {{ test }}"` would result in a simple array with the name `['test']`.
With this I could check, if the incoming parameters `?test=foo&another=bar` cover all parameters in the template string.

I found the `strict_mode`, but this doesn't provide the flexibility I would like to have, in respect to proper and exact error handling. 

If you find such a functionality helpful, I would like to add it to your library and I would be happy about any hints on how to implement this feature :)

Thanks for providing this library!

**Comment by sunng87** [comment]
Hi, it's actually possible in current release of handlebars. You can get a template struct from `Handlebars.get_template(name)` and access the template elements in `elements` field. The variable is of type `Expression`, together other types you might be interested in.

**Comment by Nukesor** [comment]
Nice! Thanks for the hint!
This will definitely do the job, but it's quite hard to find, though ;).
