### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by sunng87** [sunng87/handlebars-rust#30]

**Comment by gsingh93** [comment]
@sunng87 Can you start this off by adding the name of the template that wasn't found to the "Template not found" `RenderError` description?

**Comment by tailhook** [comment]
+1, I don't think the template engine is usable without even tiny bit of error reporting.

**Comment by sunng87** [comment]
I understand. Just need some time for this. Pull requests are always welcomed.

**Comment by sunng87** [comment]
Error report and line_no has been added to 0.11.0 and released to crates.io. I will close this.
