### ISSUE TITLE
Compile error with the 2.0.3 update

### ISSUE THREAD

**Issue by leudz** [sunng87/handlebars-rust#304]
Hi! I use the mdbook crate and it stopped compiling today, very likely due to handlebars' update.

I don't know much about both projects but here's the error:

<details>
<summary>Error</summary>

    Compiling mdbook v0.3.5
    error[E0277]: `(dyn std::error::Error + 'static)` cannot be sent between threads safely
    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbook-0.3.5/src/lib.rs:123:5
        |
    123 | /     error_chain! {
    124 | |         foreign_links {
    125 | |             Io(std::io::Error) #[doc = "A wrapper around `std::io::Error`"];
    126 | |             HandlebarsRender(handlebars::RenderError) #[doc = "Handlebars rendering failed"];
    ...   |
    156 | |         }
    157 | |     }
        | |_____^ `(dyn std::error::Error + 'static)` cannot be sent between threads safely
        |
        = help: the trait `std::marker::Send` is not implemented for `(dyn std::error::Error + 'static)`
        = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
        = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
        = note: required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + 'static)>>`
        = note: required because it appears within the type `handlebars::error::RenderError`
        = note: required because it appears within the type `errors::ErrorKind`
        = note: required because it appears within the type `errors::Error`
        = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

</details>

Since the update was a patch, the issue is more to report the breaking change than anything else.

[Here](https://github.com/rust-lang/mdBook/issues/1124)'s the issue in mdbook.

**Comment by wez** [comment]
I'm also here because mdbook no longer compiles.
I believe that https://github.com/sunng87/handlebars-rust/commit/cc26933f0f9aa8f30a9f2983a546ae19ef845e76 should have bumped the version of the package to `2.1` because it changed the interface of the crate in a backwards incompatible way.
I'd suggest:

1. Yank 2.0.3 ASAP
2. Either:
    * publish the 2.x branch as 2.1
    * Restore the `Send`-ability of the error type and publish 2.0.4

**Comment by udoprog** [comment]
Upgrade broke for me as well, 2.0.3 should definitely be yanked.

In case anyone is curious:
`Send` and `Sync`: https://docs.rs/handlebars/2.0.2/handlebars/struct.RenderError.html#impl-Send
`!Send` and `!Sync`: https://docs.rs/handlebars/2.0.3/handlebars/struct.RenderError.html#impl-Send

**Comment by sunng87** [comment]
Sorry, 2.0.3 has been yanked.

**Comment by udoprog** [comment]
Thanks for the quick action @sunng87 ❤️

**Comment by sunng87** [comment]
@udoprog @wez by the way, are you using handlebars with any web framework?

**Comment by udoprog** [comment]
No, just for internal templating here:
https://github.com/udoprog/OxidizeBot/blob/master/bot/src/template.rs
It's used for all kinds of things though.

**Comment by wez** [comment]
> @wez by the way, are you using handlebars with any web framework?

Not directly: I use mdBook to build the docs for http://wezfurlong.org/wezterm/.
Thanks for yanking :-)

**Comment by sunng87** [comment]
Thanks you guys so much for quick reporting! 

@udoprog It seems you have extensive usage of the template API. Always let me know your questions or suggestions of it. By the way, in order to improve render performance, there will be minor changes about the template API.

**Comment by Dylan-DPC** [comment]
Thanks for the quick response, Since 2.0.3 is yanked, it would be better to release a new patch version (2.0.4) :)

**Comment by sunng87** [comment]
The fix has been released in `2.0.4`. I have tested on mdbook, OxidizeBot and my own handlebars-iron.
