### ISSUE TITLE
Issue creating helper with macro

### ISSUE THREAD

**Issue by ctron** [sunng87/handlebars-rust#305]
Using the default example for registering a custom helper:

~~~
handlebars_helper!(hex: |v: i64| format!("0x{:x}", v));
~~~

Results in the following error for handlebars version `3.0.0-beta.5` and `3.0.0-beta.4` for me:

~~~
error[E0107]: wrong number of type arguments: expected 1, found 2
  --> src\main.rs:19:1
   |
19 | handlebars_helper!(hex: |v: i64| format!("0x{:x}", v));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unexpected type argument
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

~~~

**Comment by sunng87** [comment]
This is weird. I actually has a test for this macro at https://github.com/sunng87/handlebars-rust/blob/master/tests/helper_macro.rs#L10

And `cargo test` says it work for me. Can you check if there is difference between the test and your code?

**Comment by sunng87** [comment]
I will close this for now. If you can reproduce this issue feel free to reopen.
