### ISSUE TITLE
Problems porting custom helper from 2.0 to 3.0

### ISSUE THREAD

**Issue by Keruspe** [sunng87/handlebars-rust#311]
In a custom `each` helper, I had this snippet:

```
let mut params = BlockParams::new();
params.add_path(block_param, &path)?;
local_rc.push_block_context(params)?;
```

where path was `local_rc.get_path().to_owned() + ".Foo"` (Foo being an enum variant, and having several possible values).

With 3.0 I now have

```
let mut params = BlockParams::new();
params.add_path(block_param, Vec::with_capacity(0))?;
block.set_block_params(params);
```

But I'm not sure how to property construct the relative path to replace the `Vec::with_capacity(0)`.
Any pointers?

Also, alongside `@index`, `@last`, etc, I'm adding another "local" variable. If I call it `argument_is_value` like I did in 2.0, it is not defined in 3.0, if I call it `@argument_is_value`, then it is properly defined. Any pointers on this one too?

**Comment by sunng87** [comment]
Have you checked my current `each` implementation?

For block parameter, the path is now relative to current block's base path. If your block parameter path was base path + `.Foo`, you just put `[".Foo".to_owned()].to_vec()` as parameter value.

For custom local variable, it's still possible to put `argument_is_value` into the context.

Do you have a link to your implementation? I can help you to port your impl.

**Comment by Keruspe** [comment]
Here is my current work for porting to 3.0 https://github.com/sozu-proxy/amq-protocol/commit/56e6bbc548689f4a1669cb9a695bd7f0e5cf6f01

`cargo test` inside of the `codegen` directory should pass once the issue is fixed.

I used your each implementation as the base for mine, yes. With current code, if I insert {{@argument_is_value}} in a template, it renders as either true or false. If I sed away the @, it becomes empty.

`[".Foo".to_owned()].to_vec()` doesn't seem to work. The path before was something like `a/b/[i].Foo`. Now if I understand correctly the path is `[a, b, i]` (and if `i` is anything else than just `index.to_string()`, like `format!("[{}]", index)` for example, I get a parsing exception).
`[a, b, i]` is like `a/b/[i]` but `[a, b, i, ".Foo"]` doesn't seem to be like `a/b/[i].Foo`

**Comment by Keruspe** [comment]
Hmm, looks like actually just `Foo` instead of `.Foo` works

**Comment by Keruspe** [comment]
`@argument_is_value` still needs its `@` though, otherwise it doesn't work

**Comment by sunng87** [comment]
@Keruspe Sorry it was my mistake. You don't need the `.` in `.Foo` for the parameter. The path vector is already segmented and separators like `/` or `.` is not needed here.

**Comment by sunng87** [comment]
> @argument_is_value still needs its @ though, otherwise it doesn't work

Yes, when you set it as a local variable you will need `@` to reference it. That was defined in handlebars syntax and the behaviour was corrected in 3.0.

**Comment by sunng87** [comment]
Actually if you want maintain backward compatibility, you can define `argument_is_value` as a block parameter, so it will always have a value in the block scope without need for `@` to reference it.

**Comment by Keruspe** [comment]
Thanks for the clarification !
I guess we can close this then as everything seems to be working now
