### ISSUE TITLE
A wiki page to list extensions

### ISSUE THREAD

**Issue by davidB** [sunng87/handlebars-rust#320]
Hi,

I would like to start a section on the wiki to list handlebars-rust "extentions and tools", maybe as a section of the adopter page or as a new wiki page. WDYT ?

I'm the creator of [davidB/handlebars_misc_helpers: A collection of helpers for handlebars (rust) to manage string, json, yaml, toml, path, file, http request.](https://github.com/davidB/handlebars_misc_helpers)

**Comment by sunng87** [comment]
Yes! Currently there is a *Related Projects* section in README that linked to your project. I have started a new wiki page you can fill in: https://github.com/sunng87/handlebars-rust/wiki/Extensions

By the way, as helper developer, your thoughts on helper API is always welcomed. Feel free to give suggestions on it.

**Comment by davidB** [comment]
The documentation (samples) was good enough for me to be able do what I want (I had to go into the source sometimes to understand better). Currently I don't understand every elements of the helper's API.

Thanks for your hard work and support.
