### ISSUE TITLE
In the Getting Started sample code, you need a return statement

### ISSUE THREAD

**Issue by josh-kean** [sunng87/handlebars-rust#324]
I was able to get the "Getting Started" code to compile by adding the following line to the bottom of the main function;

std::result::Resut::Ok(())

I think this should be added to the docs so more people can compile this on their first go. I don't mind doing a PR to make this change =)

**Comment by sunng87** [comment]
Good catch. Feel free to create a PR for this. It's always welcomed.

**Comment by sunng87** [comment]
Fixed in 5f624152
