### ISSUE TITLE
Support array indexing

### ISSUE THREAD

**Issue by gsingh93** [sunng87/handlebars-rust#33]
It would be nice if templates could support the array indexing syntax described [here](https://stackoverflow.com/questions/8044219/handlebars-access-array-item).

Also, can the `{{lookup}}` helper be used with integer literals as the indices? It seems like the answer is no, this would also be nice to have.

**Comment by gsingh93** [comment]
More info on this syntax here: http://handlebarsjs.com/expressions.html

**Comment by sunng87** [comment]
Will look into this later. Currently I'm pretty busy so if you get a pull request for this, it's welcomed.

**Comment by sunng87** [comment]
expression like `a.b.[1]` and `a.b.[#comments]` are fully supported now.

I will look into `{{lookup}}` helper later.

**Comment by sunng87** [comment]
implemented be2f163
