### ISSUE TITLE
What to use instead of Context::navigate now?

### ISSUE THREAD

**Issue by Boscop** [sunng87/handlebars-rust#334]
I want to upgrade from v1 to v3 of this crate.
Inside a datetime helper, I have the following code:
```rust
let timezone = ctx
    .navigate(".", &VecDeque::new(), "timezone")?
    .ok_or_else(|| RenderError::new("timezone is missing in context"))?;
```
Is this the recommended way to do this now, or is there a more convenient way (not having to match `Value::Object`)?
```rust
let timezone = match ctx.data() {
    Value::Object(map) => map.get("timezone"),
    _ => None,
}
.ok_or_else(|| RenderError::new("timezone is missing in context"))?;
```

--- 

2: Why does `Handlebars` need a lifetime now?

**Comment by Boscop** [comment]
I'm now using this function:
```rust
fn lookup_var<'a>(ctx: &'a Context, var: &str) -> Option<&'a Value> {
    ctx.data().as_object().and_then(|obj| obj.get(var))
}
```
But it would be nice if `Context` had a convenience method for that.

**Comment by sunng87** [comment]
For `navigate`, it now has deep involvement with internal stuff so I choose to hide it from user.

Do you think  `{{helper_name timezone}}` work for you? I will resolve `timezone` from current context for you. And you will be able to retrieve its value by `h.param(0).value()`

For the second question, it was discussed in #281 in case you have borrowed data in your helper.
