### ISSUE TITLE
Support for named args in `handlebars_helper` macro?

### ISSUE THREAD

**Issue by Boscop** [sunng87/handlebars-rust#335]
It seems it's currently not possible to use the `handlebars_helper` macro for defining helpers with optional named args.
Could support be added by using `hash_get`? :)

The syntax for these args could be `arg: Option<Type>` or `arg=Option<Type>`.

**Comment by sunng87** [comment]
Good idea! Are you interested in proposing a pull request for this feature?

**Comment by Boscop** [comment]
@sunng87 Probably not unfortunately, as I am currently very busy..

**Comment by sunng87** [comment]
No problem. I will add it to my backlog.
