### ISSUE TITLE
Which handlebars version does it implement?

### ISSUE THREAD

**Issue by Boscop** [sunng87/handlebars-rust#336]
Which handlebars.js version does this crate implement?
(The current version of handlebars.js is 4.7.6)

It would be useful to have a table in the Readme that shows which version of this crate matches which version of handlebars.js.

**Comment by sunng87** [comment]
My version doesn't attempt to implement a particular version of handlebars. The version number of this crate has no relation with js one. 

There are some feature this crate doesn't implement and a few implemented in a different way.

**Comment by Boscop** [comment]
Where are the differences documented? :)

**Comment by sunng87** [comment]
There is a section in doc. https://docs.rs/handlebars/3.1.0/handlebars/#compatibility-with-original-javascript-version

But I believe it didn't cover all cases. If you have compatibility issue you can post here.

**Comment by Boscop** [comment]
Thanks!

**Comment by Boscop** [comment]
@sunng87 Btw, what do you meant by "mustache blocks" in that section?

**Comment by sunng87** [comment]
@Boscop see https://github.com/janl/mustache.js handlebars was derived from this syntax. And they use `{{#people}}`, given `people` is an array, to iterate over it. While in handlebars, we mostly use `{{#each}}` helper to do that. 

However, `{{#people}}` was supported  by handlebars.js but not by handlebars-rust
