### ISSUE TITLE
built-in helper `each` could not work with derived JSON value as parameters

### ISSUE THREAD

**Issue by chaserhkj** [sunng87/handlebars-rust#343]
Running the following code snippet

```rust
//# handlebars = "3.1.0"
//# serde_json = "*"

#[macro_use]
extern crate serde_json;

use handlebars::Handlebars;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let data = json!(4);
    let hb = Handlebars::new();

    let template = "{{#each [0,1,2] as |i|}}{{i}}{{/each}}";
    println!("{}", hb.render_template(template, &data)?);
    Ok(())
}
```

Produces output `444` instead of `012`

**Comment by sunng87** [comment]
Bug confirmed. Thanks for reporting

**Comment by sunng87** [comment]
It seems literal param with `each` doesn't work in handlebars.js either.

**Comment by chaserhkj** [comment]
Oh, I was not expecting that from handlebars.js...

But putting literals aside, if a small helper is used, the inconsistency with handlebars.js is then confirm-able.

In handlebars.js:

With
```javascript
Handlebars.registerHelper('range', function (aInt) {
    return [...Array(aInt).keys()]
})
```

Rendering  `{{#each (range 3) as |i|}}{{i}}{{/each}}` from data `4` could produce `012`

But another code snippet using handlebars-rust:

```rust
//# handlebars = "3.1.0"
//# serde_json = "*"

#[macro_use]
extern crate serde_json;

#[macro_use]
extern crate  handlebars;

use handlebars::Handlebars;
use std::error::Error;

handlebars_helper!(range: |x: u64| (0..x).collect::<Vec<u64>>());

fn main() -> Result<(), Box<dyn Error>> {
    let data = json!(4);
    let mut hb = Handlebars::new();
    hb.register_helper("range", Box::new(range));

    let template = "{{#each (range 3) as |i|}}{{i}}{{/each}}";
    println!("{}", hb.render_template(template, &data)?);
    Ok(())
}
```

Would still produce `444` instead of `012`.

So I suppose this is still some bug in `each`

**Comment by chaserhkj** [comment]
I just dig a little deeper into this and realized that the problem is `each` helper is not handling arguments with derived JSON values (as in `ScopedJson` ) correctly. Changing the argument in the helper from a derived value to a value from the data model would workaround this.

And for `with` it would work without any problem. So probably you need to copy the logic dealing with block parameters from `with` ([here](https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/helper_with.rs#L37)) to `each([here](https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/helper_each.rs#L67)).

Would love to do a PR myself but I'm on a close deadline for my papers, so I am using some workarounds instead. I could get back to help fix this after my deadline if it's not fixed then...

**Comment by sunng87** [comment]
Thank you! Agreed that producing `444` is not a correct behaviour.

Your PR is welcomed. I'd love to see more patches from contributors.  So I will leave this issue open for you. Always let me know if you need any help with the internals of handlebars-rust.

**Comment by chaserhkj** [comment]
PR submitted, PTAL
