### ISSUE TITLE
Expressions in {{else}} blocks fail with "invalid digit found in string"

### ISSUE THREAD

**Issue by Aeledfyr** [sunng87/handlebars-rust#344]
Whenever an expression is used after `{{else}}` in an `{{#each}}` loop, an error is returned with "invalid digit found in string".  I'm not experience with handlebars, but this appears to work in handlebars js playground, so I would expect it to work here as well, or at least have a better error message.

Here is a minimal example:
```rust
#[macro_use]
extern crate serde_json;

fn main() {
    let reg = handlebars::Handlebars::new();
    let template =
"{{#each list}}
A
{{else}}
{{foo}}
{{/each}}";
    let input = json!({"list": [], "foo": "bar"});
    let rendered = reg.render_template(template, &input).unwrap();
    println!("{}", rendered);
}
```

After looking at more handlebars documentation, I see that it should have been `{{../foo}}`, which works, but I would expect a better error message, it that is possible.

**Comment by sunng87** [comment]
Thanks for reporting. This happens when accessing an array with string as key. However, there is an issue with the context path in else block.
