### ISSUE TITLE
Partial Parameters Not Working

### ISSUE THREAD

**Issue by duckman** [sunng87/handlebars-rust#345]
I'm trying to get parameters working with partials as described in https://handlebarsjs.com/guide/partials.html#partial-parameters.
```
use handlebars::Handlebars;

fn main() {
    let one = "This is a test. {{> two name=fred }}";
    let two = "Lets test {{name}}";
    
    let mut handlebars = Handlebars::new();
    
    handlebars.register_template_string("one", one).unwrap();
    handlebars.register_template_string("two", two).unwrap();
    
    let data = {};
    let result = handlebars.render("one", &data).unwrap();
    
    println!("{}", result);
}
```
I'm expecting `This is a test. Lets test fred` but am getting `This is a test. Lets test`

Sorry if I am missing something simple, but I've been fighting this for hours.

**Comment by sunng87** [comment]
You need to use `name="fred"` to assign `name` as a string. Otherwise handlebars-rust will try to resolve `fred` as a reference in current context.

**Comment by duckman** [comment]
That makes total sense... Sorry for the silly question. :)

**Comment by sunng87** [comment]
Never mind. I'll think about how to improve debug experience for cases like this.
