### ISSUE TITLE
Reusing everying but Templates when rendering them

### ISSUE THREAD

**Issue by dynaxis** [sunng87/handlebars-rust#351]
Is `'ref` required in `&'ref self` in `render` method of `Renderable` trait?

I was trying to reuse everything but the templates. So I put a `Registry`, a `Context`, and a `RenderContext` into a struct and compiled template strings each followed by a call to its `renders` method.

But due to the `'reg` lifetime in `&'reg self` in the method, I ended up just reusing `Context` for all of the template strings.

I guess it should be possible by removing `'reg` from `self`. Am I doing something wrong?

**Comment by sunng87** [comment]
@dynaxis could you please provide me some of your code? Actually `Renderable` was designed to be an internal API so the compatibility might not be guaranteed. Also it would be nice if you describe your design and the issue you were trying to resolve.

**Comment by dynaxis** [comment]
@sunng87 oh, that's unfortunate to hear that the relevant APIs are not intended for public use.

```rust
struct Merger {
    context: Context,
}

impl Merger {
    fn new(params: &BTreeMap<String, String>) -> Merger {
        Merger {
            context: Context::wraps(params).unwrap(),
        }
    }

    fn merge(&self, s: &str) -> Result<String, TemplateRenderError> {
        let template = Template::compile(s)?;
        let mut registry = Handlebars::new();
        registry.register_escape_fn(no_escape);
        registry.set_strict_mode(true);
        let mut render_context = RenderContext::new(None);

        Ok(template.renders(&registry, &self.context, &mut render_context)?)
    }
}
```

In the above code, I actually wanted to move both `Registry` and `RenderContext` into `Merger` together with `Context`. I parse YAML files and want to interpret only some of the values as possible Handlebars templates. As you see, I have no choice but to compile templates from strings, render them, and throw them away. But at least, I thought I don't need to create `Registry`, `Context`, and `RenderContext` over and over again.

Any idea?

**Comment by sunng87** [comment]
Well, you are using a few internal APIs. I would suggest to make `Registry`(`Handlebars`) shared because if you don't register any template, it will be completely stateless. You don't need to recreate it.

Second, I would not suggest to use `RenderContext` and `Template` because it's mostly internal. Why not just use `registry.render_string`?

It seems I can add a API for registry to render from a `Context` struct. 

Do you have benchmark about the cost of `Context::wrap`? If I recall correctly, it doesn't cost to much so you can simply cache the BTreeMap instead of `Context`.

**Comment by dynaxis** [comment]
@sunng87 Thank you for your insightful comments and the time spent.

First, I was a bit confused. If I leave out the `RenderContext`, then my code works. So except for the fact that it's using some internal APIs, I'm more or less satisfied. 

Second, I don't have any benchmark yet. I know the `data` is directly converted into a `Value` via a special `Serializer` by `serde_json`, but wanted to avoid the overhead involved since I use it repeatedly without any change and it may grow in size in some cases.

I'm not sure if it's worth adding support for managing `Context`s like `Template`s.

But if it's ok to expose `Context`, then maybe it's more than enough to add `render` variants accepting `Context` directly.

And as another idea, as I mentioned in my last comment, it may be worthwhile to introduce a default data. If it exists, I might be able to overuse it for my purpose.

If you think no immediate change to the crate is strictly necessary, then feel free to close this issue.

Thank you again.

**Comment by sunng87** [comment]
I agree. I'm going to add at least one  variant of the render methods that accepts `Context` to avoid the copy.

**Comment by sunng87** [comment]
After the benchmark it turns out I was wrong. The `Context::wraps` operation takes up to 50% time for our benchmark.
