### ISSUE TITLE
Serialized Mongodb documents can't reference _id property

### ISSUE THREAD

**Issue by No9** [sunng87/handlebars-rust#357]
Hi Again
I've been looking at building on the the tide support by integrating it with mongodb and have come across an issue.

When objects have been inserted with no identifier Mongodb defaults a `bson::oid::ObjectId`

However when this type is serialized as JSON it has a `$` in the object name.
e.g. 
```
[{"_id":{"$oid":"5f0f87cf4aa5235f13ee10c8"},"name":"New York","country":"USA"}]
```
Apparently this is valid JSON but when I try to use it in a template with `this._id.$oid` 
The following error is thrown
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TemplateError(TemplateError { 
reason: InvalidSyntax, template_name: Some("home"), line_no: Some(18), column_no: Some(32), segment: Some("  
15 |                     </form>\n  
16 |                     -->\n  
17 |                     {{this._id.$oid}}\n     |--------------------------------^----\n  
......
src/main.rs:22:5
```

Is this expected behavior or should we try and support this format of JSON?

Thanks for your time considering this question and let me know if anything isn't clear.

**Comment by sunng87** [comment]
It should be caused by our parser that doesn't accept `$` as symbol char. This can be fixed soon.

**Comment by sunng87** [comment]
For now, you can use `this._id.[$oid]` to  skip this issue.

After some investigation, support for $ in property name slightly conflicts with the dollar expression. I need some time to get into the original mustach spec for detail.

**Comment by No9** [comment]
Thanks for `this._id.[$oid]` - That's unblocked me
Looking at the spec https://handlebarsjs.com/guide/expressions.html#literal-segments it would seem as though the current behavior is expected.
Maybe just a bit more detail in the error message is required.

**Comment by sunng87** [comment]
Actually handlebarsjs 4.0 has support for `$` in key. Thanks for the spec and I will add support for `@` and more chars.

The error message was directly generated by our parser. But it seems we can probably add more information for the rule it breaks.

**Comment by sunng87** [comment]
It seems I misunderstood the spec, that `@` is not allowed as symbol char while `$` should be supported  by native. #359 fixes this issue and also an error in mustache syntax implementation.
