### ISSUE TITLE
support "mass" rendering

### ISSUE THREAD

**Issue by ihrwein** [sunng87/handlebars-rust#36]
If I have a lot of templates and I want to render all of them with the same context It may be useful to convert the parameter into JSON once and use it on every templates. That would spare a `to_string()` in `renderw()`.

If you are open for this feature I think I can contribute it.

**Comment by sunng87** [comment]
If I understood correctly, you can convert your parameter to JSON once, because JSON itself is `ToJson`.

**Comment by ihrwein** [comment]
I'd like to spare the multiple `to_json()` calls on the context. For example, if I have a `Registry` with `1000` templates and I'd like to render every one of them with the same context with the current API there is no way to reduce that thousang `to_json()` calls into one.

**Comment by sunng87** [comment]
Although the [ToJson implementation](https://github.com/rust-lang/rustc-serialize/blob/master/src/json.rs#L2371) for Json is just a clone, it's reasonable to avoid this waste. What will your API look like?

**Comment by sunng87** [comment]
Perhaps we can just change the `render` function (or add another one) to accept a `Json` instead of `ToJson`

**Comment by ihrwein** [comment]
Here it is: https://github.com/sunng87/handlebars-rust/pull/37

**Comment by ihrwein** [comment]
You can check the new `render_iter()` method. It can spare the multiple `to_json()` calls and even some `to_strings()`.

Maybe that new `render_*()` function would stand on it's own as a good idea as well.

**Comment by sunng87** [comment]
Supported in #39
