### ISSUE TITLE
. no longer works in partial names

### ISSUE THREAD

**Issue by quantimnot** [sunng87/handlebars-rust#367]
Hello,

I've been using you software for some time with partials that contain a `.`

The breaking change came from #362.

P.S.
Thank you for this wonderful piece of software.

**Comment by sunng87** [comment]
Thank you for reporting. Just verified `.` is allowed in partial name. I will fix this soon.

**Comment by sunng87** [comment]
Fixed in 5abfb19 

It will be released in 3.4. You can stick with 3.2 for now.
