### ISSUE TITLE
Skip unhandled expressions

### ISSUE THREAD

**Issue by Armiixteryx** [sunng87/handlebars-rust#374]
Hello. First, I want to thank you for your work in this library!

Actually when handlebars-rust founds an unknow expression it skips the whole expression. For instance:

```rust
use handlebars::Handlebars;
use std::collections::BTreeMap;

fn main() {
    let mut handlebars = Handlebars::new();

    // handlebars.register_template_string("greet", "hello {{world}}").unwrap();
    handlebars.register_template_string("greet", "hello {{mundo}}").unwrap();
    let mut data = BTreeMap::new();
    data.insert("world", "humans");

    println!("I got: {}", handlebars.render("greet", &data).unwrap());
}
```

Will render: `I got: hello`

I want to know if it is possible to skip unknow expressions to render this output instead: `I got: hello {{mundo}}`

Putting `{{mundo}}` inside raw blocks (e.g. `{{{{raw}}}}{{mundo}}{{{{/raw}}}}` ) is not an option for me. The reasons are that the expressions will not be rendered at the same time, in other words, I will render the templates many times and {{{{raw}}}} blocks just survive one render, and the templates I am processing should contain some expressions that will be rendered later outside of my program.

Thank you for any help in this :)

**Comment by sunng87** [comment]
I see. Not sure if handlebars.js has solution for this. If we really want to support this, maybe some meta resolver like `valueMissing` can help.

**Comment by sunng87** [comment]
After checking handlebarjs docs, this behaviour should be covered by `helperMissing` hook. I will add support for this in next release.

**Comment by sunng87** [comment]
@Armiixteryx Just realized this is already supported in handlebars-rust. There is a testcase to describe this: https://github.com/sunng87/handlebars-rust/blob/master/src/render.rs#L1094
