### ISSUE TITLE
Helper and variable precedence

### ISSUE THREAD

**Issue by tmpfs** [sunng87/handlebars-rust#377]
Hi @sunng87 , I just ran into a small issue where it seems like a variable is taking precedence over a helper with the same name. I have a workaround by just renaming the helper however I checked the [docs](https://handlebarsjs.com/guide/block-helpers.html#basic-blocks) and it appears that helpers should always take precedence and I can disambiguate to a variable using `./` notation. From the docs:

> Any helpers defined in this manner will take precedence over fields defined in the context. To access a field that is masked by a helper, a path reference may be used. In the example above a field named noop on the context object would be referenced using:

I will try to create an MVP that reproduces the issue.

Thanks!

**Comment by tmpfs** [comment]
My bad, I tried to create an MVP failed to reproduce the problem and then realized that I needed to upgrade handlebars in my project.

Upgrading to `3.3` fixed the issue for me. Apologies for the bother, closing as not an issue.

**Comment by sunng87** [comment]
Yes. This issue was addressed in 3.3. Thanks for reporting. Feel free to ask any question when using this library.
