### ISSUE TITLE
Strict mode does not fail on missing iterable

### ISSUE THREAD

**Issue by ThouCheese** [sunng87/handlebars-rust#384]
Hi! I'm using strict mode to validate whether templates are correct. This works great, since it makes the rendering fail when the template does not match the provided context. However, when a context is used with `#each`, the rendering does not fail. This can be reproduced as follows:

```rust
fn main() {
    let template = "hello {{#each messages}} {{ this}} {{/each}}";
    let ctx: std::collections::HashMap<String, String> = Default::default();
    let mut handle = handlebars::Handlebars::new();
    handle.set_strict_mode(true);
    let res = handle.render_template(template, &ctx).unwrap();
    println!("{}", res);
}
```
The output is `hello`, but the expected output would but what I expect would be a `RenderError` saying something like `"Variable \"messages\" not found in strict mode."`.

**Comment by sunng87** [comment]
Currently the strict enforcement was only applied when we are rendering something. 

I think you are right. It makes sense to throw a `RenderError` when 

- the value is not iterable
- and there is no `{{else}}` block defined
