### ISSUE TITLE
dont url encode

### ISSUE THREAD

**Issue by luke-titley** [sunng87/handlebars-rust#392]
Is there an option to disable url encoding.
I'm using handlebars to generate c++ code and it's turning:
```c++
Vec2<float>
```

into
```
Vec2&lt;float&gt
```

**Comment by sunng87** [comment]
@luke-titley you can use following code to disable html escaping:

```rust
use handlebars::{self, Handlebars};

let mut hbs = Handlebars::new();
hbs.register_escape_function(handlebars::no_escape);
```

You can also use handlebars html expression syntax  `{{{ ... }}}` to disable escaping for particular expression.

**Comment by luke-titley** [comment]
k, thanks

**Comment by jknight** [comment]
hbs.**register_escape_function**(handlebars::no_escape);
