### ISSUE TITLE
Documentation on {{#each}} syntax missing

### ISSUE THREAD

**Issue by matthiasbeyer** [sunng87/handlebars-rust#399]
The documentation for handlebars is generally really good, but I miss the documentation how to write `{{#each}}` blocks.
Would be lovely to get an update for the docs, I had to read the source to understand how it works, which is unfortunate, IMO.

**Comment by sunng87** [comment]
hi @matthiasbeyer , for the syntax part, handlebars-rust tries best to align with the [original javascript version](https://handlebarsjs.com/guide/) so in most case I didn't write my own version of the document. 

However, questions about the language are always welcomed. Feel free to raise questions here and I can help with anything inside or outside this library. It also help me to identify  ergonomic issue with the api or docs.

**Comment by sunng87** [comment]
Link for the `each` helper https://handlebarsjs.com/guide/builtin-helpers.html#each

**Comment by matthiasbeyer** [comment]
I already found out how to do it.
Maybe it would be a good idea to just link the individual handlebarsjs sites from the documentation, for better discoverability?

**Comment by matthiasbeyer** [comment]
Fixed as of 3e3de3261d422172431b8c0cd0f612bbd5ce94e9
