### ISSUE TITLE
Triple stash excaping potential bug

### ISSUE THREAD

**Issue by freiguy1** [sunng87/handlebars-rust#4]
I'm sending a string of html in the model.  Say it looks something like this:

`{ body : "<h1>hello</h1>\n<p>world</p>" }`

`{{{body}}}` would get rendered like this:

> # hello
> \n
> world

in the browser.  The '\n" actually shows up when the page is rendered.  Instead, I think \n's should just be new lines in html, not \\n in the html string.

Thanks!

**Comment by freiguy1** [comment]
It looks like it's escaping other things it shouldn't like apostrophes.  I have html that shows up like 

` <h3 id=\"hello-world!\" class='section-header'>` when using triple stash

**Comment by sunng87** [comment]
Thanks for reporting. I will make a test case for this and look into it later today. Seems to be a bug.

**Comment by freiguy1** [comment]
Thanks for checking into these!  I think the issue is around [here](https://github.com/sunng87/handlebars-rust/blob/f53e4b16cdd62f1988235c73a45607333e6643d1/src/context.rs#L110).  You may want to somehow replace all \\n, \\r, \\", \\\\, \\t strings with the escaped version.  Maybe you have a fancier way of trying it out.  I guess this is just how the json lib formats strings: [http://is.gd/GFqmML](http://is.gd/GFqmML)

**Comment by sunng87** [comment]
I'm using the fmt function to render Json values. And it did something more for `Json::String. Perhaps I will just add a special case for `Json::String` and get the content instead of using `fmt` directly, see http://is.gd/avzd6o

**Comment by freiguy1** [comment]
That looks great!

**Comment by sunng87** [comment]
This issue should be fixed. Please run `cargo update` to get latest build.

Also I'm quite interested in your project. If you meet any issue with handlebars, please let me know.

**Comment by freiguy1** [comment]
Thanks a lot! I'm working on a project that will generate a static website using an arbitrarily complex structure of nested markdown files and directories. Mainly for taking notes and being able to deploy/keep a history via git.  It's similar to the jekyll idea but less blog-like.  For the time being, a working version is at [notes.ethanfrei.com](http://notes.ethanfrei.com).
