### ISSUE TITLE
Errors from render_template have themselves as source - reopen #398

### ISSUE THREAD

**Issue by SuperCuber** [sunng87/handlebars-rust#402]
Opened this since I cannot reopen issue #398 .

Tested on commit 996ada2aed6aa80277b2c4d6bb2008fd1c353083 and the bug is still there.

**Comment by sunng87** [comment]
@SuperCuber  I've updated [the error example](https://github.com/sunng87/handlebars-rust/blob/master/examples/error.rs#L30) but still cannot reproduce your issue, the output for `render_template`:

```
Failed to parse template.
Template error: invalid handlebars syntax.
    --> Template error in "Unnamed template":1:8
     |
   0 | {{#if}}
     |-------
     |
     = reason: invalid handlebars syntax.

None
```

**Comment by SuperCuber** [comment]
Seems like this is fixed in https://github.com/sunng87/handlebars-rust/commit/4c667c78cdbdeeb56ec1cf26650950a61e4928fc (it wasn't on `=3.5.2`)

**Comment by sunng87** [comment]
Yes, since it is break change I won't port it to 3.x branch.
