### ISSUE TITLE
Register partials directory method request

### ISSUE THREAD

**Issue by Lykos94** [sunng87/handlebars-rust#407]
Since there is the ```register_templates_directory``` method, it would be useful if there was also a method to register the partials inside a directory. I could help on this feature if help is needed

**Comment by sunng87** [comment]
You should be able to templates from `register_templates_directory` as 
partials. Let me know if you have any issue with that.

**Comment by Lykos94** [comment]
Yes, it looks like it's working! Thank you :+1:
