### ISSUE TITLE
question - can i register a helper to resolve multiple templates/data on demand instead of pre calculating all data which might not be necessary

### ISSUE THREAD

**Issue by avnerbarr** [sunng87/handlebars-rust#410]
I don't know all of the templates to be rendered ahead of time so i'd like a function which will resolve for any value on the fly - (especially for some which are expensive to calculate and are not necessary for many templates.)
currently I just add all values to the data, even those which are unused.

cheap to create
`"hello {{user_name}}" `

more expensive:
`"hello {{user_name}}, {{some_expensive_expression_from_database}}"`

I'd like to have a function that resolves everything when it is requested:

(pseudo)
```
let mut reg = Handlebars::new();
reg.register_helper("resolve anything", resolve);
reg.render_template("hello {{user_name}}, this is very expensive to calculate {{some expensive thing here}}" , resolve);
fn resolve(template: &str) -> String {
  if template == "user_name" ...
  if template == "some expensive thing to calculate" ....
  ...
}
```

**Comment by sunng87** [comment]
Yes. Actually you can access the `Handlebars` registry from helper function, where you can access and render any template that registered.
