### ISSUE TITLE
Can you render a template to a JSON structure instead of a string?

### ISSUE THREAD

**Issue by rnhurt** [sunng87/handlebars-rust#414]
I'm very new to Rust so I'm sorry if this is a silly question.  My application is a AWS CloudFormation template generator and I'm running into an issue with rendering templates to JSON instead of string.  

The general flow of my application is:
1. render a GLOBALS template to set global things (AWS account number, IP addresses, AWS region information, etc.)
2. apply that GLOBALS context to each .hbs template
3. render each .hbs template as a JSON file

Currently, I'm rendering the GLOBALS to a string, converting it to JSON, and using that to render the templates.  This works but it feels forced and seems like there should be a better/easier way to do it.  Is it possible to render a .hbs template to a JSON structure instead of a string?  Or maybe I'm doing the wrong thing and there is a better way to accomplish this.

Sample Code
```
    hbs.register_template_file("globals", "./globals.hbs")?;
    hbs.register_template_file("test", "./test.hbs")?;
    let mut output_file = File::create("test.template")?;

    // this conversion seems wrong, unnecessary
    let globals_str = hbs.render("globals", &Json::Null)?;
    let globals: Json = serde_json::from_str(&globals_str)?;

    hbs.render_to_write("test", &globals, &mut output_file)?;
```

**Comment by sunng87** [comment]
You are doing it right. The conversion is needed because template engine can only deal with text. 

But you may want to generate this `GLOBALS` JSON data by set values into a Rust data structure instead of a template. But if the data structure is complex enough, it's OK to doing it your way. There are a lot of applications using this library to generate rust code.

**Comment by rnhurt** [comment]
@sunng87,

Thank you for the feedback!  The JSON data structure is quite complicated and able to change at any time so it's probably not a good idea to convert it into a Rust data structure.  :thinking: 

BTW: Thank you so much for making this library.  I really like it so far and am looking forward to using more Rust in the future!  :heart:
