### ISSUE TITLE
Block Params

### ISSUE THREAD

**Issue by wycats** [sunng87/handlebars-rust#42]
Any plans to add support for Handlebars block params?

**Comment by sunng87** [comment]
Wow, @wycats, thanks for analyzing this library. 
I didn't know this block param feature before. I will add support in future releases.

https://github.com/emberjs/rfcs/blob/master/text/0003-block-params.md

**Comment by mmun** [comment]
I would encourage anyone who is interested and has the time to attempt to implement this feature. Block params an important part of the handlebars language! Let me know if you need details on the semantics beyond what is described in the document linked above.

**Comment by sunng87** [comment]
This has landed to master via #101
