### ISSUE TITLE
Request: "#if" helper blocks on empty lines should consume newlines for block in render

### ISSUE THREAD

**Issue by elmiko** [sunng87/handlebars-rust#426]
When using an `#if` helper where the opening (`{{#if condition}}`) and closing (`{{/if}}`) tags are on lines by themselves, the rendered output should consume the newlines for the tags. For example, the [Handlebars documentation on the "if" helper](https://handlebarsjs.com/guide/builtin-helpers.html#if) shows the newlines being consumed around the tags.

A [similar example](https://gist.github.com/elmiko/2d30b02e3c78fea89ee24df0e84e9f1f) written to use handlebars-rust produces slightly different output:

```
$ cargo run
   Compiling hbsoutput v0.1.0 (/home/mike/dev/sandbox/rust/hbsoutput)
    Finished dev [unoptimized + debuginfo] target(s) in 0.53s
     Running `target/debug/hbsoutput`
---
<div class="entry">

<h1>Yehuda Katz</h1>

</div>
---
<div class="entry">

</div>
---
```

As a handlebars-rust user, this feature would be really nice when using templates that are sensitive to newline spacing with dynamic content.

**Comment by sunng87** [comment]
@elmiko This should have been fixed on upcoming 4.0 release. You can use `4.0.0-beta.2` to verify it.

**Comment by elmiko** [comment]
i will give that a try, thanks @sunng87 !

**Comment by elmiko** [comment]
i ran the same program against the 4.0.0-beta.2 version and it definitely looks better.

```
$ cargo run
    Updating crates.io index
   Compiling handlebars v4.0.0-beta.2
   Compiling hbsoutput v0.1.0 (/home/mike/dev/sandbox/rust/hbsoutput)
    Finished dev [unoptimized + debuginfo] target(s) in 4.06s
     Running `target/debug/hbsoutput`
---
<div class="entry">
<h1>Yehuda Katz</h1>
</div>
---
<div class="entry">
</div>
---
```

there is still a minor difference with the example from the handlebars docs, but i'm happy to close this issue. thanks again!
