### ISSUE TITLE
Accessing fields of a ScopedJson returned by helper

### ISSUE THREAD

**Issue by ilyazzz** [sunng87/handlebars-rust#433]
Maybe I'm misunderstanding how objects returned by helpers are supposed to be used, but I was unable to access the fields of an object that my custom handler returns.

I have a helper that looks like this:
```rust
impl HelperDef for MyHelper {
    fn call_inner<'reg: 'rc, 'rc>(
        &self,
        _: &Helper<'reg, 'rc>,
        _: &'reg Handlebars,
        _: &'rc Context,
        _: &mut RenderContext<'reg, 'rc>,
    ) -> Result<Option<ScopedJson<'reg, 'rc>>, RenderError> {
        Ok(Some(ScopedJson::Derived(json!({
            "a": 1,
            "b": 2,
        })))
}
```
I'm not sure what would be the proper way to access "a" and "b" from it. I have tried using `{{ myhelper["a"] }}`, but it seems to always return `[object]`, regardless of accessing the entire helper object or one of it's fields. How do I access the value in it as a string?

**Comment by sunng87** [comment]
@ilyazzz I'm afraid `{{myhelper["a"]}}` is not valid handlebars expression. You can test it on the playground from javascript version: http://tryhandlebarsjs.com/

To implement your scenario, you can try `lookup` with subexpression, like:
```handlebars
{{ lookup (myhelper) "a" }}
```

**Comment by ilyazzz** [comment]
I have tried using lookup, but it doesn't seem to work.

Here's a minimal example. It doesn't print out anything, and I'm not sure why:
```rust
use handlebars::{Context, Handlebars, Helper, HelperDef, RenderContext, RenderError, ScopedJson};
use serde_json::json;

fn main() {
    let mut registry = Handlebars::new();

    registry.register_helper("myhelper", Box::new(MyHelper {}));

    let result = registry.render_template("{{ lookup (myhelper) \"a\" }}", &TemplateContext {}).unwrap();
    
    println!("{}", result) ;
}

struct MyHelper;

impl HelperDef for MyHelper {
    fn call_inner<'reg: 'rc, 'rc>(
        &self,
        _: &Helper<'reg, 'rc>,
        _: &'reg Handlebars,
        _: &'rc Context,
        _: &mut RenderContext<'reg, 'rc>,
    ) -> Result<Option<ScopedJson<'reg, 'rc>>, RenderError> {
        Ok(Some(ScopedJson::Derived(json!({
            "a": 1,
            "b": 2,
        }))))
    }
}

#[derive(serde::Serialize)]
struct TemplateContext;
```
This is a working basic helper in javascript, where the same template syntax does work:
```js
Handlebars.registerHelper('myhelper', function (value) {
  return { "a": 1, "b": 2 }
});
```

**Comment by sunng87** [comment]
Let me look into this. It seems to be a bug with `lookup` helper

**Comment by sunng87** [comment]
Confirmed there is a bug with parser that it cannot recognize subexpression with no parameters. For now, you can workaround this with `{{lookup (myhelper 0) "a" }}`

**Comment by ilyazzz** [comment]
`if` also seems to be affected, where `{{ #if (myhelper) }}` doesn't work and `{{ #if (myhelper 0) }}` does

**Comment by sunng87** [comment]
@ilyazzz could you please verify this behaviour with our latest `master`?

**Comment by ilyazzz** [comment]
@sunng87 yes, it seems to work properly within my `with` expression now. Thank you.
