### ISSUE TITLE
Enhancement - Simplify rendering unregistered precompiled Templates (i.e. export handlebars::StringOutput)

### ISSUE THREAD

**Issue by jeremychone** [sunng87/handlebars-rust#442]
## Problem

Today only `handlebars::output::StringOuput` is private and not exported as `Output` is. This probably makes sense, but it does make rendering precompiled unregistered `Template`a a little bit cumbersom. 

The good news is that `handlebars::Output` is exported and the Context/RenderedContext APIs are simple to use, so duplicating the StringOutput's few lines was not too much work to work around this limitation. 

## Suggestions

Would be nice to just export `handlebars::StringOutput`  similarly to `handlebars::Output`. 

#### Optional

Perhaps, adding another `registry.render_with...(&compiled_template, ...)` method for convenience. But in a way, if users want to get that advanced, it is not an issue to have to create the Context / RenderContext object. 

P.S. Anyway, feel free to close if I missed something or this requirement is not in line with lib priorities. Great lib!

**Comment by sunng87** [comment]
@jeremychone sorry for late response. While it's ok to export `StringOutput`, I'm a little curious about the scenario for skipping registration of a template. Could you describe your use case for that?

**Comment by jeremychone** [comment]
@sunng87 very sorry for late answer, I thought I responded but I did not. 

So, I do not have this need anymore because I am doing it in another way, but I still think there is a valid use case for it. 

Sometimes, we may have some more complex documents that have multiple sub template parts that can be used independently. So, the document is "string addressable", but not necessarily handlebars one, while some of its parts might be. Now, one way is to come up with an artificial naming scheme for those parts to be cacheable by handlebars, but better to just store those pre-compiled parts in the appropriate struct/enums and use them with the appropriate context when needed. 

I simplified my current case for other reasons, but I still think this is a valid use-case, which I might use at some point. 

(to be more precise on my use case, is a meta-document for Kubernetes files, so the Kubernetes files are handlebars, but the meta-document was not a full handlebars document but just part of it was)

Hope this gives some information. Anyway, great lib. All good, copying few lines is ok.

**Comment by sunng87** [comment]
Understood. The reason we hold a strong opinion to cache template is to support features like partial inclusion and template inheritance. These features lookup template from the registry and include them into render process. If templates are not managed by a central registry, it may cause troubles to find them.  

I'm closing this for now. Feel free to rise any other questions about the library.

**Comment by jeremychone** [comment]
@sunng87 I understand and value the partial and template inheritance, I am not sure it's mutually exclusive and I actually see the two mode rather additive. Sometime, you might have a model where you do not need the "leaf" templates to be referred/used in anyway. 

Anyway, as long as we can create our own StringOutput, that's fine.

**Comment by sunng87** [comment]
No problem. I will export `StringOutput` in next release.
