### ISSUE TITLE
Empty Vector results in "variable not found" error in 4.0.0

### ISSUE THREAD

**Issue by matthiasbeyer** [sunng87/handlebars-rust#446]
Hi,

my code broke with the update to 4.0.0 and I don't know why this is happening. It _seems_ that handlebars fails to find a variable in the input of my `Handlebars::render()`, but the variable is clearly there (I debug-print the whole datastructure before passing it to handlebars).

I tried to file an PR which tests this in #445 but CI told me I was wrong... I don't see why it breaks in my code!
Compiling a minimal example seems to fail (see #445), so here's the pieces in my codebase:

* The struct that gets passed to `render()`: https://git.sr.ht/~matthiasbeyer/butido/tree/master/item/src/package/package.rs#L29
* The `render()` call: https://git.sr.ht/~matthiasbeyer/butido/tree/master/item/src/package/script.rs#L235

The variable we're talking about is `patches`.

Maybe you can see where my error is right away? If not... I'm not sure how to proceed here. 

---

Edit: To show where I'm printing the `Package` struct:

* https://git.beyermatthi.as/butido/tree/src/package/package.rs?h=try-update-handlebars#n160
* https://git.beyermatthi.as/butido/tree/src/package/script.rs?h=try-update-handlebars#n236

**Comment by matthiasbeyer** [comment]
So it seems that I have found the issue:

https://github.com/sunng87/handlebars-rust/runs/2828438291?check_suite_focus=true
This workflow run shows that in strict mode, an empty vec is reported as "not found" if there is no `else` block in the template.

I am preparing a patch right now to fix this. I hope I can manage to make it work properly - I hope we agree that a template without `else` should still render an empty array correctly (so the resulting string should be empty)!?

**Comment by sunng87** [comment]
Fixed in 445
