### ISSUE TITLE
Vanishing newlines

### ISSUE THREAD

**Issue by vojtechkral** [sunng87/handlebars-rust#457]
I think the change at #404 might've been too aggressive, given a template like this:
```hbs
      {{~#if condition}}
        foo
        bar
      {{/if}}
    baz
```
~~I get no newline between `bar` and `baz` anymore. I believe there should be one. A workaround is to add a comment right after the closing if, ie. `{{/if}}{{!}}`.~~
But for now I think I'll hold the update to 4.x ...

This is probably tricky to solve correctly.

**Comment by vojtechkral** [comment]
S imilar issue is with inline partials.
This:
```hbs
{{#*inline "foo"}}foo
{{/inline}}
{{> foo}}
{{> foo}}
{{> foo}}
```
Should render the foos with newlines inbetween (currently that is not the case).

**Comment by sunng87** [comment]
@vojtechkral for case 

```handlebars
      {{~#if condition}}
        foo
        bar
      {{/if}}
    baz
```

I cannot reproduce the issue as you described for newline between bar and baz. You can check [the commit](https://github.com/sunng87/handlebars-rust/commit/745148da7974e5c87103654d6e92247b14ad83d9) to see if it matches your scenario. However there is a bug with additional newline added ahead of foo and it's fixed in #458 

I will be digging into your second case soon

**Comment by sunng87** [comment]
@vojtechkral could you help to verify it's handlebars 4.1 on which these issues happened? Changes in #404 could have affected your cases but should have been fixed in 4.1 with #448 . Although I managed to fix some corner cases in #458 but none of them are related to your scenario.

**Comment by vojtechkral** [comment]
@sunng87 I'll try

**Comment by vojtechkral** [comment]
@sunng87 Yeah, it looks like the `if` case is gone or wasn't there in the first place, I think I might've relied on pre- #458 behvaiour. Sorry about that.

The `inline` case is still there it seems, in [this file](https://github.com/vojtechkral/bard/blob/main/example/templates/hovorka.hbs#L35) the inline `i-break` doesn't work anymore on 4.1

**Comment by vojtechkral** [comment]
Hm... however, it looks like the behavior is the same now as in JS handlebars. So, looks like I was relying on nonstandard thing there as well.
Ok, I'll close the bug and update my code.
