### ISSUE TITLE
dev mode activation needs to go before registration

### ISSUE THREAD

**Issue by upachler** [sunng87/handlebars-rust#459]
Hello,

I'm not sure if this is a bug or me overlooking something in the docs, or an undocumented feature:

When trying to wire dev mode into my app, I discovered that `hb.set_dev_mode()` needs to go before `hb.register_templates_directory()`. If `register_templates_directory()` comes first, you're in for a surprise (spoiler: it won't work; changed templates won't reload).

I suggest that either:
* the documentation for `set_dev_mode()` is changed so that it says that it needs to go first, or at least before `register_*()` (the easy way forward)
* `register_*()` is changed so that it will accept being called before `set_dev_mode()` and still respect it (harder; that's what my expectation was as a library user)
* I am corrected for reporting a non-bug ;-)

Cheers,
Uwe

**Comment by sunng87** [comment]
Thank you for reporting. This is actually a missing part in our docs.

**Comment by sunng87** [comment]
Fixed in 3d495f8
