### ISSUE TITLE
Feature: Macros

### ISSUE THREAD

**Issue by untitaker** [sunng87/handlebars-rust#46]
https://stackoverflow.com/questions/17934477/macros-in-handlebars

Perhaps I'm missing something, but registering a helper seems a little "too flexible" for my usecase. In particular, I would like to write the content of my helper/macro/don't-care in handlebars itself, and avoid having to take care of HTML escaping myself.

**Comment by sunng87** [comment]
This quite similar to our current partial system, check this test for the inline partial: https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/helper_partial.rs#L151

Of course, currently parameters are not supported on `block` helper.

**Comment by untitaker** [comment]
I see, this is close to what I want except for the lack of parameters. I suppose I could combine `block` with `with` to emulate "passing" a single argument.
