### ISSUE TITLE
Generic parameter in `handlebars_helper` does not compile.

### ISSUE THREAD

**Issue by bugadani** [sunng87/handlebars-rust#460]
Because the `handlebars_helper` macro uses `$tt`, the macro fails to compile in the following case:

```rust
handlebars_helper!(date_helper: |dt: DateTime<Utc>| dt.format("%F"));
```

```
error: no rules expected the token `<`
   --> src/bin.rs:119:50
    |
119 |     handlebars_helper!(date_helper: |dt: DateTime<Utc>| dt.format("%R"));
    |                                                  ^ no rules expected this token in macro call
```

**Comment by sunng87** [comment]
Right. Can you open a pull request for this? 

I haven't look into the macro system, is there a replacement for `$tt` to support this?

**Comment by bugadani** [comment]
Normally, `$ty` should be able to match a type but handlebars supports some interesting syntax using `$tt` so this isn't a simple search and replace problem. I'm not comfortable with handlebars to try and fix it just yet.
