### ISSUE TITLE
Unable to include html in handlebars_helper

### ISSUE THREAD

**Issue by madelaney** [sunng87/handlebars-rust#471]
I'd like to write a `handlebars_helper` in which takes a `str` and replaces all new lines (`\n`) with an HTML line break (`<br />`). However, it appears that the HTML is getting escaped into `&lt;` and `&gt;` (respectively).

The help code that I'm using looks like this:
```rust
handlebars_helper!(nl_to_br: |s: str| {
    s.replace("\n", "<br />")
  }
);
```

Is there a way to not have the `<` and `>` escaped out?

- Mike D.

**Comment by sunng87** [comment]
A quick fix for this is to call the helper with `{{{nl_to_br text}}}`. 

You can also define the helper by implementing `HelperDef` trait by yourself, which you can use the `Output` API to skip html escape.

**Comment by madelaney** [comment]
@sunng87  Thanks for the quick reply. However, when I try to invoke the helper with triple brackets, I get a syntax error:

```
Error: TemplateError { reason: InvalidSyntax, template_name: Some("changelog"), line_no: Some(38), column_no: Some(46), segment: Some("  35 |         {{#each release.changes as |change|~}}\n  36 |           {{#each change.messages as |message|}}\n  37 |             <div class=\"message\">{{{nl_to_br message}}}</div>\n     |----------------------------------------------^--------------\n  38 |           {{/each~}}\n  39 |         {{/each~}}\n  40 |       </div>\n  41 |     </div>\n") }
Exit 1
```

**Comment by madelaney** [comment]
I believe I have something working but I'm new to handlebars within Rust so I'm not sure if it's the most elegant approach, any feedback would be appricated:

```rust
use handlebars::{
  Context, Handlebars, Helper, HelperDef, JsonRender, Output, RenderContext, RenderError,
};

#[derive(Clone, Copy)]
pub struct NewLineRetainer;

impl HelperDef for NewLineRetainer {
  fn call<'reg: 'rc, 'rc>(
    &self,
    h: &Helper,
    _: &Handlebars,
    _: &Context,
    _: &mut RenderContext,
    out: &mut dyn Output,
  ) -> Result<(), RenderError> {
    let param = h
      .param(0)
      .ok_or(RenderError::new("Param 0 is required for format helper."))?;
    let mut rendered = format!("{}", param.value().render());
    rendered = rendered.replace("\n", "<br />");
    out.write(rendered.as_ref())?;
    Ok(())
  }
}

pub static NLBR_HELPER: NewLineRetainer = NewLineRetainer;


```

**Comment by sunng87** [comment]
@madelaney the helper looks good. 

I just created a test to demo the helper call within a triple brackets expression: https://github.com/sunng87/handlebars-rust/commit/dd6dcdd84f78a12f97893dc58aa6ea14a792ec1f . Also please make sure you are using the latest version of handlebars-rust library.

**Comment by madelaney** [comment]
Thanks @sunng87 , I think there are enough alternative paths that we can close this out.
