### ISSUE TITLE
Partials do not respect the indentation from source content

### ISSUE THREAD

**Issue by nswarm** [sunng87/handlebars-rust#482]
Partial calls only use indentation defined in the partial template itself.

### Example

inner.hbs
```hbs
name: {{name}}
```

outer.hbs
```hbs
                {{> inner inner_solo}}

{{#each inners}}
                {{> inner}}
{{/each}}

        {{#each inners}}
        {{> inner}}
        {{/each}}

```

main.rs
```rs
use std::error::Error;
use handlebars::Handlebars;
use serde_json::json;

fn main() -> Result<(), Box<dyn Error>> {
    env_logger::init();
    let mut hbs = Handlebars::new();

    hbs.register_template_file("inner", "./templates/inner.hbs")?;
    hbs.register_template_file("outer", "./templates/outer.hbs")?;

    let result = hbs.render("outer", &json!({
        "inner_solo": {"name": "inner_solo"},
        "inners": [
            {"name": "hello"},
            {"name": "there"}
        ]
    }))?;
    println!("{}", result);

    Ok(())
}
```

Result:
```txt
name: inner_solo

name: hello
name: there

name: hello
name: there
```

### Handlebars JS Handling
Handlebars js by default uses the indentation of the partial call itself, but has a compiler flag to disable this functionality, see `preventIndent` in the [Handlebars.compile options.](https://handlebarsjs.com/api-reference/compilation.html#handlebars-compile-template-options)

### Use Case
I'm using recursively nested partials to render a tree view, so specifying indentation in the target template itself does not work.

--

Thanks for your hard work!

**Comment by nswarm** [comment]
I've worked around my use case for with a custom block helper that explicitly injects indentation into its rendered content.

**Comment by sunng87** [comment]
Thank you for reporting! I will look into my template parser to see if `preventIndent` can be supported.

**Comment by TheButlah** [comment]
#486 does not appear to have actually solved this. If the next put into the partial spans multiple lines, the next line does not keep the same indentation as the first line.

Also, it appears as though none of the tests for indentation in partials test what happens if the string that is going to be used for the render spans multiple lines.

**Comment by TheButlah** [comment]
Can this please be reopened? Or should I file a new issue?

**Comment by sunng87** [comment]
@TheButlah could you please provide me a demo template for reproducing this?

**Comment by sunng87** [comment]
I've created #504 to track this.

**Comment by TheButlah** [comment]
> @TheButlah could you please provide me a demo template for reproducing this?

Sorry, I just saw this! It looks like you solved it though :)
I'll post in #504  if I have any further bugs
