### ISSUE TITLE
Vanishing newlines

### ISSUE THREAD

**Issue by xuzn** [sunng87/handlebars-rust#489]
Cargo.toml
```toml
[dependencies]
handlebars = "4.2.0"
serde_json = "1.0.74"
```

tests.rs
```rust
#[test]
fn test_template() {
    use handlebars::Handlebars;
    use serde_json::json;
    let reg = Handlebars::new();
    let expect = "[\n    1,\n    2,\n    3,\n    4,\n]";
    let template_string = "[
    {{~#each items as |item|}}
    {{item}},
    {{~/each}}
]";
    let data = json!({"items": [1,2,3,4]});
    let result = reg.render_template(template_string, &data).unwrap();
    assert_eq!(expect, &result);
}
```
cargo test
```shell
failures:

---- test_template stdout ----
thread 'test_template' panicked at 'assertion failed: `(left == right)`
  left: `"[\n    1,\n    2,\n    3,\n    4,\n]"`,
 right: `"[    1,    2,    3,    4,]"`', tst/tests/tests.rs:14:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sunng87** [comment]
@xuzn it seems the behaviour is consistent with [the original javascript version](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%5B%5Cn%20%20%20%20%7B%7B~%23each%20items%20as%20%7Citem%7C%7D%7D%5Cn%20%20%20%20%7B%7Bitem%7D%7D%2C%5Cn%20%20%20%20%7B%7B~%2Feach%7D%7D%5Cn%5D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20items%3A%20%5B1%2C2%2C3%2C4%5D%5Cn%7D%5Cn%22%2C%22output%22%3A%22%5B%20%20%20%201%2C%20%20%20%202%2C%20%20%20%203%2C%20%20%20%204%2C%5D%5Cn%22%2C%22preparationScript%22%3A%22%2F%2F%20Handlebars.registerHelper('loud'%2C%20function(string)%20%7B%5Cn%2F%2F%20%20%20%20return%20string.toUpperCase()%5Cn%2F%2F%20%7D)%3B%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D). 

You may need additional new lines between `[` and `{{#each` for your case

```handlebars
[
    {{~#each items as |item|}}
    
    {{item}},
    {{~/each}}
    
]
```
