### ISSUE TITLE
Partial indent should apply to every line of partial string

### ISSUE THREAD

**Issue by sunng87** [sunng87/handlebars-rust#504]
[Case](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23*inline%20%5C%22thepartial%5C%22%7D%7D%5Cn%20%20inner%20first%20line%5Cn%20%20inner%20second%20line%5Cn%7B%7B%2Finline%7D%7D%5Cn%20%20%7B%7B%3E%20thepartial%7D%7D%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20firstname%3A%20%5C%22Yehuda%5C%22%2C%5Cn%20%20lastname%3A%20%5C%22Katz%5C%22%2C%5Cn%7D%5Cn%22%2C%22output%22%3A%22%20%20%20%20inner%20first%20line%5Cn%20%20%20%20inner%20second%20line%5Cn%22%2C%22preparationScript%22%3A%22%2F%2F%20Handlebars.registerHelper('loud'%2C%20function(string)%20%7B%5Cn%2F%2F%20%20%20%20return%20string.toUpperCase()%5Cn%2F%2F%20%7D)%3B%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D) to reproduce this issue.

Given

```hbs
{{#*inline "thepartial"}}
  inner first line
  inner second line
{{/inline}}
  {{> thepartial}}
```

Expected result:

```
    inner first line
    inner second line
```

Current implementation:

```
    inner first line
  inner second line
```

**Comment by mmun** [comment]
This fix doesn't seem to work correctly if there is a block, e.g. `{{#if}}` within the partial. The content inside the block is not indented.

**Comment by sunng87** [comment]
@mmun can you give me a full example to reproduce? Thank you!
