### ISSUE TITLE
Is it possible to define expression-helper?

### ISSUE THREAD

**Issue by samuelpilz** [sunng87/handlebars-rust#516]
The [handlebars documentation](https://handlebarsjs.com/guide/builtin-helpers.html#sub-expressions) allows something along the lines of:

```js
Handlebars.registerHelper('isdefined', function (value) {
  return value !== undefined;
});
```
```
{{#if (isdefined value1)}}true{{else}}false{{/if}}
{{#if (isdefined value2)}}true{{else}}false{{/if}}
```

Is this possible with this library?

**Comment by sunng87** [comment]
Never mind. Let me improve the docs of the custom helper support.
