### ISSUE TITLE
Whitespace in content removed completely.

### ISSUE THREAD

**Issue by mainrs** [sunng87/handlebars-rust#521]
My template looks like this:

```handlebars
---
to: crates/cli/src/prompts/mod.rs
insert:
  type: regex
  pattern: INSERT PROMPT VARIANT HERE
  position: before
---
    {{ to_pascal_case name }}({{ to_pascal_case name }}Prompt),
```

I create my `ParsedEntityStruct` like this:

```rust
let rendered = hb_instance
    .render_template(&content, &context)
    .wrap_err_with(|| "Failed to render template")?;
 let parsed = matter.parse_with_struct::<Frontmatter>(&rendered)
    .wrap_err_with(|| "Does the frontmatter have syntax errors or unsupported fields?")?;
```

The whitespace at the start gets removed. `parsed.content` contains `MyName(MyNamePrompt)` only.

**Comment by mkantor** [comment]
What library are you using to parse out front matter (where does `matter.parse_with_struct` come from)? I imagine that's eating the whitespace, not this library. You can confirm by inspecting the contents of `rendered`.

**Comment by sunng87** [comment]
@mainrs like @mkantor said, could please verify if `rendered` is as you expected?
