### ISSUE TITLE
Why is registry private?

### ISSUE THREAD

**Issue by franklinblanco** [sunng87/handlebars-rust#531]
<img width="815" alt="Screen Shot 2022-09-16 at 12 40 47 PM" src="https://user-images.githubusercontent.com/72827992/190688141-da1cdacc-e8a9-4783-b9ce-6ba6466f3507.png">
I want to register all my templates on server start. I made this method but realized I can't return Registry from a method because even though it is public the base package registry is private. Why is this the case? Are we supposed to register all the templates each time we want to access them or am I doing something wrong?

**Comment by sunng87** [comment]
`Registry` is exposed with name `Handlebars`. Just use `handlebars::Handlebars` for registry.
