### ISSUE TITLE
Integration with oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by manunio** [sunng87/handlebars-rust#535]
Hi @sunng87, I would like to help integrate this project into [OSS-Fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/8649, it contains necessary logic from an OSS-Fuzz perspective to integrate handlebars-rust.

- OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects.

- As handlebars-rust already have cargo-fuzz based fuzzing implemented, this makes it easily compatible with oss-fuzz out of box.

-  If you would like to integrate, the only thing I need is a list of email(s), it must be associated with a google account like 
gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the     provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

- As an alternative, if you don't have a google/gmail id, but still wish to integrate. I can add my mail id for time being and monitor bug/crashes.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by sunng87** [comment]
@manunio Thank you for your proposal! Although we had some fuzz test config but we did not pass the test. As a template engine our input is typically something looks like a handlebars template. At least for now, I think fuzz test does little help to improve the library.

**Comment by sunng87** [comment]
I just moved our unmaintained fuzz tests. 

Anyway, thank you very much for investigating oss-fuzz for handlebars-rust.
