### ISSUE TITLE
Issue with handlebars-rust 4

### ISSUE THREAD

**Issue by mojindri** [sunng87/handlebars-rust#540]
Hi, 
i have this code {{eq image.link null}} in a partial template,  image.link: is an object that i pass through as JSON object, and whenever is null, this expression should output true, this code used to work with handlebars 3.5.5 well, but with latest version of handlebars, i face this issue  : [..helper: Couldn't read parameter x],  same issue i see also for 
{{ someHelper "15px" (not image.disable) "24px" }} , (not image.disable)  doesnt work here
regards,
moji

**Comment by sunng87** [comment]
There are some changes for partial context in 4.0. It seems you have strict_mode turned on and `image.link` is null. Could you please provide me some more context about your partial and how you pass data into partial?

**Comment by mojindri** [comment]
hi @sunng87 ,
sure!, 
i pass data(serialisable serde) using .render function as part of its argument,  and handlebars-rust kinda iterate the data and binds it to corresponding partial template, 
----
one question is it possible somehow to tell handlebars to ignore null variables in strict_mode?
thanks for support :) 
moji

**Comment by sunng87** [comment]
Do you have a minimal example to reproduce this?

**Comment by mojindri** [comment]
Hi @sunng87 , 
sorry for late answer,
the issue is coming from my side, strict_mode was true, and that casued so much confusion,
regards,
moji
