### ISSUE TITLE
Lazy initialize a variable

### ISSUE THREAD

**Issue by kpcyrd** [sunng87/handlebars-rust#550]
hello!

I currently have templates like this:

```
/foo/{{sha256}}
```

and I calculate this hash (and a few others) in advance. Now, for performance reasons I don't want to calculate these values in advance anymore and instead have a `sha256: Option<String>` that gets lazy initialized on access, so only the hashes that are used are calculated, but only once.

Is there any documentation on how to do this?

**Comment by sunng87** [comment]
Hi @kpcyrd , you can make sha256 a helper so it calls some rust code when rendering

**Comment by kpcyrd** [comment]
Is there an example somewhere? :) I'm having trouble creating a helper that works with no arguments.

**Comment by sunng87** [comment]
See https://github.com/sunng87/handlebars-rust/blob/master/tests/data_helper.rs

It should be similar as normal helper.

**Comment by kpcyrd** [comment]
Thank you, I got it to work. :) My working solution can be found here:

https://github.com/kpcyrd/sh4d0wup/commit/8004fe66c3e794390f110c274542d164319f10f5

The only difference where it doesn't behave like a "lazy variable" was when combining it with another helper. Instead of:
```
{{slice-until sha1 2}}
```

I had to write:
```
{{slice-until (sha1) 2}}
```

I hope this thread is useful to others. Cheers!
