### ISSUE TITLE
How do I generate a single brace?

### ISSUE THREAD

**Issue by jm-observer** [sunng87/handlebars-rust#580]
for example, data: 
```
{"name": "abc"}
```
desired outcome:
```
{abc}
```
how to design this template?

**Comment by sunng87** [comment]
Good question. Perhaps there is a handlebar escape expression for this, but the easiest way into my mind to create a helper say `format` and write the template as `{{format name}}`. And you can find how to implement a format helper here https://github.com/sunng87/handlebars-rust/blob/master/examples/render.rs#L16
