### ISSUE TITLE
version 4.3.7 seems to be broken due to pest 2.5.6 (semver violation)

### ISSUE THREAD

**Issue by turboMaCk** [sunng87/handlebars-rust#582]
Hello. Thanks for working on this library!

I just tried to used it in one of my project. Cargo automatically resolved to version 4.3.7 but it failed to compiled due to transitive dependency on pest parser which resolved to 2.5.6 which failed to compile due to this known issue https://github.com/pest-parser/pest/issues/849

Perhaps it might be worth releasing patch for the issue? I don't yet have a workaround for the issue - the fix will require pinpointing the transitive dependency of pest to specific version though the question is how this could be done.

**Comment by turboMaCk** [comment]
It seems that `5.0.0-beata.2` suffers from the same issue.

**Comment by sunng87** [comment]
@turboMaCk just to confirm with version do you want me to resolve to, `2.5.x` or `2.6.0`?

**Comment by sunng87** [comment]
Thank you for the information. Actually I'm not a big fan of pinned dependencies in a library. I'm worrying that it could bring in more problems than it resolves. Have you tried to pin the version in your application project?

**Comment by turboMaCk** [comment]
@sunng87 see the comment above.

> The workaround that works is to add dependecy on pest with pin version as:
>
> ```
> pest = { version = "=2.5.6" }
> ```
>
> to the project.

This is how you can pin the pest dependency from the project using handlebars (provided you understand how what the issue is and how to resolve it downstream). Every new project which will want to add this library will probably need to do this or something similar to this.

I think it would be worth fixing things upstream rather than letting downstream project to deal with the issue. Anyway real upstream is pest in this case. In the end I personally don't care that much since I've already been able to work around the issue and can't personally do anything to prevent others from having to through the same (other than providing the info above) anyway so I don't really feel invested in this. Feel free to close the issue if you don't feel like patching this on side of handlebars.
