### ISSUE TITLE
Provide a way to directly render files

### ISSUE THREAD

**Issue by svenstaro** [sunng87/handlebars-rust#60]
This one might be controversial given your design. My idea here is that currently rendering something is more verbose than it needs to be. I would like something like this:

`handlebars.render("templates/index.hbs", &data);`

as opposed to having to manually register the template first. I don't think the registry adds any benefit here. In fact, I think, I think it is an unnecessary layer of indirection (at least to the user). I recognize it might make sense from an implementation point of view but I'm not knowledgeable enough about your library to judge that.

**Comment by sunng87** [comment]
In this library, every template should have a name so they can be referenced in `include` and `partial` helpers. This is why we have a `Registry` that maintains all templates. 

Follow the rust philosophy, this library just focuses on template parsing and rendering. I want to keep the base API monolithic for its function. So the `render` method won't do template parsing for convenience. 

Perhaps you can compose some high-level APIs from my base API, just like what I did in [handlebars-iron](https://github.com/sunng87/handlebars-iron)

**Comment by sunng87** [comment]
I will close this for now. Feel free to reopen if you still have any question about this. Thanks!

**Comment by sunng87** [comment]
I just implemented this in 507a3c4
