### ISSUE TITLE
Each loop not aligned with inline

### ISSUE THREAD

**Issue by htakao** [sunng87/handlebars-rust#600]
When looping through items in each with inline, that not aligned.

```
use handlebars::Handlebars;
use serde_json::json;

fn main() {
    let reg = Handlebars::new();

    let tpl = r#"
<!-- without inline -->
<ul>
  {{#each a}}
    <li>{{this}}</li>
  {{/each}}
</ul>

<!-- with inline -->
{{#*inline "li"}}
{{#each a}}
  <li>{{this}}</li>
{{/each}}
{{/inline}}
<ul>
  {{> li}}
</ul>
"#;

    println!(
        "{}",
        reg.render_template(tpl, &json!({"a": [0, 1]})).unwrap()
    );
}
```
Output
```
<!-- without inline -->
<ul>
    <li>0</li>
    <li>1</li>
</ul>

<!-- with inline -->
<ul>
    <li>0</li>
  <li>1</li>
</ul>
```
It works fine in handlebars.js.
[Handlebars.js Playground](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23*inline%20%5C%22li%5C%22%7D%7D%5Cn%7B%7B%23each%20a%7D%7D%5Cn%20%20%3Cli%3E%7B%7Bthis%7D%7D%3C%2Fli%3E%5Cn%7B%7B%2Feach%7D%7D%5Cn%7B%7B%2Finline%7D%7D%5Cn%3Cul%3E%5Cn%20%20%7B%7B%3E%20li%7D%7D%5Cn%3C%2Ful%3E%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7Ba%3A%20%5B0%2C%201%5D%7D%5Cn%22%2C%22output%22%3A%22%3Cul%3E%5Cn%20%20%20%20%3Cli%3E0%3C%2Fli%3E%5Cn%20%20%20%20%3Cli%3E1%3C%2Fli%3E%5Cn%3C%2Ful%3E%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.8%22%7D)
</br>

**Comment by sunng87** [comment]
This should be duplicated as reported in #573. I'm still seeking for an elegant solution for this. Attempted in #574

**Comment by htakao** [comment]
Sorry for taking up your time. Thank you.
