### ISSUE TITLE
`DirectorySourceOptions` is not exposed publicly due to its containing module being private

### ISSUE THREAD

**Issue by HTGAzureX1212** [sunng87/handlebars-rust#602]
I currently use the `Handlebars::register_templates_directory` API which in `5.0.0-beta.3` requires a parameter of type `DirectorySourceOptions` to be passed into.

I cannot use this type as it is not exposed, resorting to a `Default::default()` call.

Is this visibility intentional?

**Comment by sunng87** [comment]
That was a mistake. Let me create a quick fix for that.

**Comment by sunng87** [comment]
Made into beta4

**Comment by HTGAzureX1212** [comment]
Thanks!
