### ISSUE TITLE
Problem with partials and #each?

### ISSUE THREAD

**Issue by euclio** [sunng87/handlebars-rust#61]
Minimal test case:

# base.hbs
```
{{ #block "layout" }}
{{/block}}
```

# index.hbs
```
{{#partial "layout" }}
{{> posts }}
{{/partial}}

{{> base }}
```

# posts.hbs
```
{{ log this }}
{{#each posts }}
{{ title }}
{{ content }}
{{/each}}
```

The log prints my context as `{ "posts": { "title": "test", "content": "test" } }`, but the rendering fails with `DEBUG:handlebars::helpers::helper_each: each value Null`. Am I doing something wrong? I'm using handlebars-iron if that helps.

**Comment by sunng87** [comment]
Hi @euclio, I cannot reproduce this issue from my code base.

Could you please should me the code about your data? It seems you are trying a render a Json string. In handlebars-rust you don't have to serialize your data into Json string. Just put the struct or map as template data will work.

And one more issue with current implementation, you cannot used quoted name in `block` and `partial`. So your index.hbs will be:

```hbs
{{#partial layout }}
{{> posts }}
{{/partial}}

{{> base }}

```

and your base.hbs

```
{{#block layout }}
{{/block}}
```

**Comment by euclio** [comment]
Ah, I was passing a string instead of `Json`. Thanks for the help!
