### ISSUE TITLE
Failure to trim non-escaped variables

### ISSUE THREAD

**Issue by ryanolson** [sunng87/handlebars-rust#616]
[Failure to trim non-escaped variables](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B~%7Bprompt%7D~%7D%7D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20%5C%22prompt%5C%22%3A%20%5C%22hi%20world%5C%22%5Cn%7D%5Cn%22%2C%22output%22%3A%22hi%20world%22%2C%22preparationScript%22%3A%22Handlebars.registerHelper('loud'%2C%20function%20(aString)%20%7B%5Cn%20%20%20%20return%20aString.toUpperCase()%5Cn%7D)%5Cn%22%2C%22handlebarsVersion%22%3A%223.0.8%22%7D)

```rust
    #[test]
    fn test_trimmed_nonescaped_variable() {
        let mut handlebars = Handlebars::new();
        handlebars
            .register_partial("system", "system: {{~{system}~}}")
            .unwrap();

        let output = handlebars
            .render_template("{{>system system=\"hello\" prompt=\" world\"}}", &())
            .unwrap();

        assert_eq!(output, "system: hello");
    }
```

This test fails.

Tested version: v3 and v4

**Comment by sunng87** [comment]
Could you please try this on `master`? I tested on v5 beta version and it should be fixed.
