### ISSUE TITLE
Support for text processing helpers

### ISSUE THREAD

**Issue by gabhijit** [sunng87/handlebars-rust#617]
When `handlebars` is used for code generation, a lot of helpers like `snake_case`, `CamelCase`, `kebab-case` etc. are useful. It will be nice if those helpers are available as an opt in feature. 

Are these helpers available? If so It''s not easy to find how use them through documentation.

**Comment by sunng87** [comment]
Sounds good to me. It's not included at the moment. Would you like to create a PR for this?

**Comment by gabhijit** [comment]
Sure, it will take some time though, as I am new to using (and hacking) `handlebars`.

**Comment by gabhijit** [comment]
Implemented in  #619

**Comment by sunng87** [comment]
Released in v4.5.0. Thank you !
