### ISSUE TITLE
ographs issue

### ISSUE THREAD

**Issue by shadowTW** [sunng87/handlebars-rust#618]
im using
```
    {{#each data}}
    <title>{{{this.title}}}</title>
    <meta name="description" content="{{{this.description}}}"/>
    <meta property="og:title" content="{{{this.title}}}"/>
    <meta property="og:description" content="{{{this.description}}}"/>
    <meta property="og:image" content="{{{this.avatar}}}"/>
    <meta property="og:url" content="https://undefined.rip/@{{{this.link}}}"/>
    <meta property="og:type" content="website"/>
    <meta name="theme-color" content="{{{this.hexcolor}}}"/>
    <link rel="stylesheet" href="/static/assets/css/landing.css">
    <link rel="icon" type="image/x-icon" href="{{this.favicon}}">
{{/each}}
```

and the opgraphs aren't appearing, I think the issue is due to rendering the file too slow
![image](https://github.com/sunng87/handlebars-rust/assets/64441627/e7fbc3c1-3111-4bc3-ae20-03d9202f8db2)

**Comment by sunng87** [comment]
hi @shadowTW, rendering data should be super fast comparing to other workload in web development. Can you check the html generated from your template and verify these meta fields?

**Comment by shadowTW** [comment]
I checked them, still the same, I tried on other ograph checkers and there it worked
maybe its due to discord

**Comment by sunng87** [comment]
Alright, it should be irrelevant with template engine. I will close this, feel free to reopen if you find anything wrong with the template engine.
