### ISSUE TITLE
After PR #619, use consistent naming of string converters

### ISSUE THREAD

**Issue by eklipse2k8** [sunng87/handlebars-rust#620]
Just to be pedantic, I think it would map better for users of serde, if the naming of the string converters matched the serde convention. 

https://serde.rs/variant-attrs.html

> Rename all the fields of this struct variant according to the given case convention. The possible values are "lowercase", "UPPERCASE", "PascalCase", "camelCase", "snake_case", "SCREAMING_SNAKE_CASE", "kebab-case", "SCREAMING-KEBAB-CASE".

**Comment by sunng87** [comment]
Thank you for the suggestion but I'm not going to introduce a breaking change for this.
