### ISSUE TITLE
Can't get the built-in `log` helper to output message

### ISSUE THREAD

**Issue by UtkarshVerma** [sunng87/handlebars-rust#626]
I have a template that I'm trying to render. It's nothing complex and contains `{{log "message"}}`. I can see that this crate does parse it and can detect an error when I set the level to an invalid value like `{{log "message" level="hola"}}`. However, I don't see my application sending the message to my terminal.

Am I missing something or is this unsupported?

**Comment by sunng87** [comment]
The `log` helper uses rust's `log` crate to write logs. Make sure:

1. You are using correct log levels: https://docs.rs/log/latest/log/enum.Level.html
2. You are using a log banckend like env_logger: https://docs.rs/env_logger/*/env_logger/

**Comment by UtkarshVerma** [comment]
Thanks, it works.
