### ISSUE TITLE
More succinct error messages for `RenderError`

### ISSUE THREAD

**Issue by UtkarshVerma** [sunng87/handlebars-rust#627]
I am developing an application where I want to be succinct about the error messages. For example, by default, the crate reports the errors in the following format:

```
Failed to parse template Template error: invalid handlebars syntax.
    --> Template error in "Unnamed":2:34
     |
   0 | * {
   1 |     color0: {{colors.normal.black};
     |----------------------------------^
   2 |     color1: {{colors.normal.red}};
   3 |     color2: {{colors.normal.green}};
   4 |     color3: {{colors.normal.yellow}};
   5 |     color4: {{colors.normal.blue}};
     |
     = reason: invalid handlebars syntax.
```

I don't want the preview of the file and only require the "invalid handlebars syntax" string. I wrote an Error wrapper and was able to get the line and column number of the error. However, I don't know how to get the `RenderErrorReason` string. Is this something that is possible?

**Comment by sunng87** [comment]
You can get `RenderErrorReason` from `RenderError`'s `.reason()` and call `.to_string()` to get its error message.
