### ISSUE TITLE
Question: App State mechanism for handlebars/helpers?

### ISSUE THREAD

**Issue by jeremychone** [sunng87/handlebars-rust#640]
_Disclaimer: I am sorry if this is already discussed, implemented, or if I missed something obvious. I could not find it in issues, examples, documentation, or code._

## Context & Proposal/Thought

The helpers seem to only have access to data in the page or context (JSON), but not to application states. There can be scenarios where the helpers (or some sort of directive) would need to fetch more data outside of the initial page context.

Would it make sense to implement a state mechanism, similar to Axum/Tauri (but simpler), so that we can "register" or "add" state by type to a Handlebars instance that can then be retrieved from the helpers function?

```rust
#[derive(Clone)]
struct MyAppState {
    some_inner: Arc<...>, // should be a clonable friend
}

let my_app_state = ....;

let mut hbs = Handlebars::new();
hbs.add_state(my_app_state);
```

And then, in the helper, we could do something like (pseudo code):

```rust
fn last_timestamp_helper(
    h: &Helper,
    hbs: &Handlebars,
    _: &Context,
    _: &mut RenderContext,
    out: &mut dyn Output,
) -> Result<(), RenderError> {
    // Get parameter from helper or throw an error
    let ext = h.param(0).ok_or(RenderErrorReason::ParamNotFoundForIndex("ext", 0))?;

    let app_state: MyAppState = hbs.get_state()?; // will error with ::StateNotFound(static_type_name)
    let last_ts = app_state.get_site_last_timestamp_for_ext(ext);

    write!(out, "{}", last_ts)?;
    Ok(())
}
```

and then, we could use this like:

```
The last TS file timestamp for this site is {{last_timestamp "ts"}}
```

The internal `handlebars.states` could be a type-map, similar to [http extensions.rs](https://github.com/hyperium/http/blob/master/src/extensions.rs) (could be much simpler), and it is up to the user to make it efficient/clonable with inner mutability if necessary.

## Notes

> Note 1: I understand this could be seen as an anti-pattern, however, for some use cases, the workaround actually leads to even more code design issues (e.g., global state, or pre/post directive processing).

> Note 2: Interestingly, in my current code base, I also have a way for templates to describe what "data" they need to have, so that the data can be fetched ahead of rendering, and this works relatively well, but for some use cases, it becomes quite cumbersome, rather than just passing a "function/helper."

> Note 3: I am sorry if this has already been discussed or if there is a way to do it in the API. I looked, searched the issues, and API.

**Comment by sunng87** [comment]
hi @jeremychone , handlebars is a stateless template engine. From my perspective, it is not recommended to store state within the template or template render flow. You'd better maintain it outside template and call `render` functions with latest/changed data.

**Comment by jeremychone** [comment]
Thanks for the answer. I understand that perspective. 

It does make it tricky for more "on-demand" type of data, but I understand the stateless benefits as well.

No problem, I can find ways to accomplish what I need.

Handlebars Rust is a great lib. Big thanks to the author and team.
