### ISSUE TITLE
Add a way for validating template data based on input

### ISSUE THREAD

**Issue by YouKnow-sys** [sunng87/handlebars-rust#641]
Let say we have a template that we always offer a set of default data arguments for. if we want to give user the ability to modify the template with a string in runtime and in same time making sure that user is using arguments that we are giving the template when rendering, we have to make sure that user is using the correct set of arguments inside the template, for that to happen we need to validate the arguments before registering the template and let user know if they are using wrong set of data inside their new template string.
currently I don't know anyway for doing this, as I seen handlebars will just use empty string in place of the variable if it don't exist...
so it would be nice if we had a solution for this as well (or is there any solution already that I don't know of?)

**Comment by sunng87** [comment]
You might want to turn on `strict_mode` on `Handlebars` to see if that fits your scenario.

**Comment by sunng87** [comment]
Oh sorry I missed that point. I think what you want is a schema for the data you are going to render in the template. However, handlebars is a weak typed template system so it doesn't come with a schema. But I think you can do it by your own, just remember to keep the schema consistent with template.
