### ISSUE TITLE
Cannot implement custom block helper: no way to access `registry::Registry`.

### ISSUE THREAD

**Issue by cmrschwarz** [sunng87/handlebars-rust#645]
The `handlebars::registry::Registry` type that is required to spell out the signature of `handlebars::HelperDef::call` (or a raw function matching the helper impl) is private. It is therefore impossible to implement this trait method.

Unless I'm missing something, it is currently impossible to create custom block helpers.

The [corresponding doc comment](https://github.com/sunng87/handlebars-rust/blob/5dda501adae4a08734b3d07ae2a27f67641613a7/src/helpers/mod.rs#L52C8-L52C19) incorrectly uses the signature of `call_inner`, which doesn't fail doctests because it is never registered as a helper at all. 

Usecase: wanted to create a custom `#repeat` for basic `for 0..N` loops.

Potential Solutions: 
1. Make the `registry` module `pub`
2. Reeport the type as `pub use crate::registry::Registry as Registry`

(plus fix the doctest to whatever was decided).

I can sent a PR myself if needed, but which solution is preferred?

**Comment by sunng87** [comment]
Registry is aliased to `Handlebars`. You can find example of custom helper here https://github.com/sunng87/handlebars-rust/blob/master/examples/render.rs

**Comment by cmrschwarz** [comment]
Duh! Sorry for missing something so obvious :sweat_smile: . In my defense the doc comment is indeed broken.
I'll send a PR improving the related docs a bit tomorrow if I manage.

**Comment by sunng87** [comment]
Never mind. Thank you for your feedback and the coming PR
