### ISSUE TITLE
png as base64 dataurl

### ISSUE THREAD

**Issue by danielclough** [sunng87/handlebars-rust#653]
When I include a dataurl it is removed in the final html.

E.g.
```html
<img src="data:image/png;base64,iVBORw0KG...ggg==" alt="alt text" />    
```
Turns into:
```html
<img alt="alt text" />    
```

Is there a way to include images in this way?

Thank You

**Comment by sunng87** [comment]
Can you provide more context with your data and your template?

**Comment by danielclough** [comment]
I will make a minimal repro when I have a moment.

**Comment by danielclough** [comment]
While creating the min repro I found my problem.

Thank you for the awesome project!
