### ISSUE TITLE
Pub use JSON crate

### ISSUE THREAD

**Issue by dbrgn** [sunng87/handlebars-rust#67]
Could you maybe "pub use" the rustc-serialize / serde JSON library that you're using? Otherwise I have to add `serde_json` as an explicit dependency to my `Cargo.toml` which might not be the same version as the one used by `handlebars`.

**Comment by sunng87** [comment]
Thanks @dbrgn ! Is this a best practice/pattern for dealing with multiple version of dependencies? I haven't used this technique in my projects. Is there any drawback for publish these crates? Is it possible to find me an example that I can follow? Thanks!

**Comment by dbrgn** [comment]
I'm not sure, but I think that's what the "pub use" feature is made for :)

I opened a similar issue in the `iron` project which was implemented: https://github.com/iron/iron/issues/406

One of the advantages is also that a `use handlebars::Json` will refer to either rustc-serialize or serde, depending on the compile flags.

**Comment by sunng87** [comment]
Since serde is widely used in user applications, and requires custom derive macro to generate code. I think we cannot do this for handlebars.
