### ISSUE TITLE
Lazy evaluation support

### ISSUE THREAD

**Issue by cbgbt** [sunng87/handlebars-rust#670]
I was wondering if it would be desirable or possible to allow Helpers to be evaluated lazily.

My specific problem is that I like to use the registry in strict mode. Since many of our template inputs are optional, this often leads to patterns where we check for existence, then process the inputs in some way. e.g.:

```handlebars
{{#if my_value}}
{{#if (is_ip_address my_value) }}
Something that depends on {{helper_fn my_value}}
{{/if}}
{{/if}}
```

Or sometimes you emit output if either of two options are set:

```handlebars
{{#if (or my_first_value my_second_value) }}
[common_section]
enable_common_option = true
{{/if}}
```

I would really love it if we could use short-circuiting boolean logic to only evaluate subexpressions if necessary. This could allow you to avoid triggering strict mode failures for branches that never evaluate:

```handlebars
{{#if (and (is_set my_value) (eq my_value "hello")) }}
{{/if}}
```

This library is excellent, by the way. Thank you so much for maintaining it!

**Comment by sunng87** [comment]
This is not possible at the moment because all helpers are implemented as function instead of macro, so all parameters are evaluated before we calling the helper.

But you particular case, I think maybe you can use the built-in `lookup` helper to bypass the strict check

```
{{#if (eq (lookup this "my_value") "hello")}}
{{/if}}
```

Do you think this will work for you ?

**Comment by cbgbt** [comment]
That's clever, thanks for the suggestion! That should work well enough for what we're doing.

**Comment by sunng87** [comment]
It's great to hear that. Thank you!
