### ISSUE TITLE
number comparison functions only accept integer values

### ISSUE THREAD

**Issue by lovasoa** [sunng87/handlebars-rust#672]
Hi !

Currently, number comparison functions only accept integer values:

https://github.com/sunng87/handlebars-rust/blob/ecef974fa1c9a445adea85e7cdf6f918e284429c/src/helpers/helper_extras.rs#L8-L11

It would be nice if they could compare any Json value with any other, or at least any number with any other.

initially reported in https://github.com/lovasoa/SQLpage/issues/573

**Comment by sunng87** [comment]
Sounds reasonable. I will look into this soon. Thank you!

**Comment by sunng87** [comment]
released in 6.1.0
