### ISSUE TITLE
Flag to preserve all newlines and original formatting

### ISSUE THREAD

**Issue by jeremychone** [sunng87/handlebars-rust#677]
## Problem

It seems that handlebars-rust is removing some newlines, which is understandable to follow the official "spec," however, it would be great if we had a way to turn this off, like `handlebars.set_preserve_newlines(true)`.

## Context

I really like handlebars and this Rust implementation, and I am using it in my devai tool to render some Agent instructions. It works like a charm, except that I noticed many of the newlines were removed, making the crafting of those precise agent instructions a little tricky.

## Possible solution

I completely understand the need to adhere to the common handlebars feature, but it would be great if we had a flag to use handlebars just as a string templating engine, preserving any whitespace and newlines from the template.

Something like:

- `handlebars.set_preserve_newlines(true)` to preserve the newlines
- or `handlebars.set_preserve_format(true)` to preserve all format elements from the original template (if more than newlines get stripped)

> Note: Sorry if I missed that API. I looked at the docs, navigated the code a bit, and did a GitHub issue search, but didn't find anything requesting that feature. (There are some newline issues, but they seem to focus more on which newlines should be removed, rather than turning off the removal entirely.)

Anyway, thanks for this great library.

**Comment by jeremychone** [comment]
Oops, that's embarrassing, it was my code.

I fixed my code, and all the newlines seem to be respected.

Sorry for the wrong alert. Handlebars is great, me not so much.

**Comment by sunng87** [comment]
No worry. Thank you for reaching out. Please let me know if you have further questions.

We really had a hard time struggling with handlebars empty spaces, newlines. In 6.0, it should be most good, aligned with original javascript implementation.

**Comment by jeremychone** [comment]
Cool, thanks for the response.

In my case, I'm not concerned about the JS implementation, as I just need it to stay true to the original template format. Basically, I’m using it purely for string templating, and so far everything works nicely. (I just set `handlebars.register_escape_fn(|s| s.to_string());`)

But yes, handling whitespaces can be tricky.

Anyway, I’m using your handlebars-rs in my DevAI command-line tool (open source as well), and it's a great fit.
