### ISSUE TITLE
Comparison functions behave incorrectly for integers larger than 2^53

### ISSUE THREAD

**Issue by cmrschwarz** [sunng87/handlebars-rust#678]
Some of the new comparison helper functions (specifically `lt`,`gt`, `lte` and `gte`) convert all numbers to `f64` before comparing them.

This leads to integers larger than 2^53 (f64 floating point mantissa is 52 bits + leading one) behaving incorrectly.

This is a breaking change from the pre-6.1 behavior, where these functions only accepted integers (and therefore handled them correctly).

Here's a simple reproduction of the issue:

```handlebars
{{#if (lt 9007199254740992 9007199254740993)}}
This should be displayed, but isn't.
{{/if}}
```

**Comment by sunng87** [comment]
Just created a PR #679 for this. I have include a new dependency `num-order` to compare numbers from different types. It's easy to go wrong with just casting.

**Comment by sahilt35-supra** [comment]
nnn
