### ISSUE TITLE
Missing {{@index}} in object iteration

### ISSUE THREAD

**Issue by lovasoa** [sunng87/handlebars-rust#681]
Hi @sunng87 !
  I use object iteration in [sqlpage](https://sql.datapage.app), and I noticed a discrepancy between handlebars.js and handlebars-rust.

```handlebars
{{#each this}}
   {{@index}}
   {{@key}}
   {{this}}
   
{{/each}}
```

parameters:
```json
{
  "firstname": "Yehuda",
  "lastname": "Katz",
}
```

expected result
```
    0
    firstname
    Yehuda
   
    1
    lastname
    Katz
```

actual result

```  
   
  firstname
  Yehuda
 
  
  lastname
  Katz
```

[try online](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23each%20this%7D%7D%5Cn%5Ct%7B%7B%40index%7D%7D%5Cn%20%20%20%20%7B%7B%40key%7D%7D%5Cn%20%20%20%20%7B%7Bthis%7D%7D%5Cn%20%20%20%5Cn%7B%7B%2Feach%7D%7D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20firstname%3A%20%5C%22Yehuda%5C%22%2C%5Cn%20%20lastname%3A%20%5C%22Katz%5C%22%2C%5Cn%7D%5Cn%22%2C%22output%22%3A%22%5Ct0%5Cn%20%20%20%20firstname%5Cn%20%20%20%20Yehuda%5Cn%20%20%20%5Cn%5Ct1%5Cn%20%20%20%20lastname%5Cn%20%20%20%20Katz%5Cn%20%20%20%5Cn%22%2C%22preparationScript%22%3A%22Handlebars.registerHelper('loud'%2C%20function%20(aString)%20%7B%5Cn%20%20%20%20return%20aString.toUpperCase()%5Cn%7D)%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.8%22%7D)

**Comment by sunng87** [comment]
I see. We only have `@index` for array. Let me add it for object as well

**Comment by sunng87** [comment]
I will cut a new release when I'm back from lunch :)

**Comment by lovasoa** [comment]
Thank you!
