### ISSUE TITLE
Enum handling

### ISSUE THREAD

**Issue by ghotiphud** [sunng87/handlebars-rust#72]
If I had an enum like:

```rust
pub enum Value {
    Float(f64),
    Bool(bool),
}
```

How would I render something like:

```html
{{#if value == Float(val)}}
    <input type='number' value={{val}} />
{{/if}}

{{#if value == Bool(val)}}
    <input type='checkbox' checked={{val}} />
{{/if}}
```

**Comment by sunng87** [comment]
I suggest you to write a helper for this.  You may check example/render.rs or src/helpers/ for sample.

**Comment by ghotiphud** [comment]
In case anyone else has a similar question I came up with this:

```html
{{#with value}}
    {{#exists Float}}
        <input name="{{../name}}" type="number" value={{this[Float]}} min=0 max=8 class="form-control input-sm"/>
    {{/exists}}
    {{#exists Bool}}
        <input name="{{../name}}" type="checkbox" {{#if this[Bool]}}checked=checked{{/if}} class="form-control input-sm" />
    {{/exists}}
{{/with}}
```

where `exists` is a helper equal to the If helper but instead of is_truthy() uses != &Json::Null.

**Comment by ghotiphud** [comment]
Also, `exists` seems like a generally useful helper.  And something like a `match` would match up well with Rust's typical idioms (excuse the pun).

**Comment by sunng87** [comment]
@ghotiphud I suggest you to make a library that implements some useful helpers in you project and publish them to crates.io. I will add a link to your library and hopefully we can curate a list like awesome handlebars helpers.

**Comment by ghotiphud** [comment]
@sunng87 Definitely like the idea, if I continue much further with this project I'll do just that. :+1:

**Comment by sunng87** [comment]
:+1:  I will close this for now. Feel free to reopen if you have any question.

**Comment by ghotiphud** [comment]
Update: 

```
{{#with value}}
    {{#exists Float}}
        <input name="{{../name}}" type="number" value={{**this.Float**}} />
    {{/exists}}
    {{#exists Bool}}
        <input name="{{../name}}" type="checkbox" {{#if **this.Bool**}}checked=checked{{/if}} />
    {{/exists}}
{{/with}}
```

had to replace array indexing with dot indexing.

**Comment by oersted** [comment]
@ghotiphud Did you end up publishing your helpers to implement this? Is there an alternative nowadays?
