### ISSUE TITLE
Hex_helper example in readme is broken + JsonRender is a private trait.

### ISSUE THREAD

**Issue by SirVer** [sunng87/handlebars-rust#76]
I think this are 2 bugs, one in the documentation and one in the library. 

Compiling the hex_helper from the readme yields:

~~~
error: the trait `core::fmt::LowerHex` is not implemented for the type `collections::string::String` [E0277]
src/bin/server.rs:135     let rendered = format!("{:x}", c.navigate(rc.get_path(), param).render());
~~~

Messing around with the code finally yields

~~~
error: source trait is private
src/bin/server.rs:137     try!(rc.writer.write(rendered.into_bytes().as_ref()));
~~~

The trait referred to here is JsonRender. The same error can be get by copy & pasting `https://github.com/sunng87/handlebars-rust/blob/master/examples/render.rs#L19`, i.e. the format_helper into a binary that is not inside the handlebars-rs crate.

**Comment by sunng87** [comment]
Thank you. As you said, this is a copy & paste error. I will fix it soon.

Also it's a good  idea to publicize `JsonRender` since it's helpful for custom helper.

**Comment by sunng87** [comment]
Just checked `JsonRender` is reexported as `handlebars::JsonRender`. You can find example from render.rs.

**Comment by SirVer** [comment]
Awesome, thanks for the documentation fix!

Turns out i was wrong about the error message, it was not complaining about JsonRender, but about `write`. I needed to  `use io::Write` which made the message go away, so no bug in handlebars-rust.
