### ISSUE TITLE
Zero param helper expression

### ISSUE THREAD

**Issue by sunng87** [sunng87/handlebars-rust#80]
Currently a helper expression with zero argument will be treated as expression. We need to treat them same at parser level and detect whether it's an expression or helper at render time.

**Comment by sunng87** [comment]
Close for now

**Comment by wezm** [comment]
I just ran into this behaviour. I created [an example case](https://gist.github.com/wezm/59202698c1f50c33d258adde87871e79) (before finding this issue) where there is a helper with the same name as a property. I expect the helper to be called but it isn't. What's your stance/suggested workaround for this?

It seems that you can force the helper to be called by supplying a param or of course just rename the helper to something else, and other ideas?

**Comment by sunng87** [comment]
@wezm Currently I think you can add a dummy parameter like `{{name _}}` to the helper so the parser will treat it as a helper instead of expression. I will improve the lookup process for fix this in future release.

**Comment by oblique** [comment]
Do you plan to have this enhancement in 2.0?

**Comment by sunng87** [comment]
I didn't but I will look into in 2.0 code context if it's easier to fix.
