### ISSUE TITLE
Partial names cannot contain hyphens after update

### ISSUE THREAD

**Issue by ghotiphud** [sunng87/handlebars-rust#84]
Pretty sure this is related to the parser updates.  Partial names could previously be of the form "pre-content" or "page-scripts", but now I've had to replace hyphens with underscores to make things work.

**Comment by sunng87** [comment]
Thank you for reporting @ghotiphud , it must be the parser update now the check is more strict. I checked handlebarsjs and found it's allowed to have `-` in partial name. So it should be supported by handlebars-rust. I will fix this later.

**Comment by sunng87** [comment]
Fixed and released in 0.18.1
