### ISSUE TITLE
register_template_file() should take the template path as an `AsRef<std::path::Path>`

### ISSUE THREAD

**Issue by casey** [sunng87/handlebars-rust#87]
If register_template_file took its path argument as an `AsRef<std::path::Path>`, then passing in a string would also work.

The new signature would be:

`fn register_template_file<P: AsRef<std::path::Path>>(&mut self, name: &str, tpl_path: P) -> Result<(), TemplateFileError>`

**Comment by sunng87** [comment]
Good idea. I will change to `AsRef<Path>`. Thank you!

**Comment by casey** [comment]
You're welcome! Thanks for the great library, by the way ^__^
