### ISSUE TITLE
Align with handlebars spec

### ISSUE THREAD

**Issue by sunng87** [sunng87/handlebars-rust#96]
https://github.com/handlebars-lang/spec

**Comment by mmun** [comment]
Hi @sunng87! If we do our job correctly shouldn't need to do any aligning :) The purpose of the spec is to decouple the language from the JavaScript implementation and allow other implementations to have a say in the evolution of the language through an RC process.

We also plan to standardize how language extensions of Handlebars like https://github.com/tildeio/glimmer/ should behave.

Feel free to contribute to the spec repository if you're interested.

**Comment by sunng87** [comment]
Thank you @mmun ! Currently there's still several incompatible things in this library with handlebars-js and the spec. It would be great if we can have an open process to evolve the handlebars language. I'm watching the spec repo and will be love to join discussions for new features.
