### ISSUE TITLE
Is `each else` working ?

### ISSUE THREAD

**Issue by Kerosene2000** [sunng87/handlebars-rust#99]
<img width="714" alt="capture d ecran 2016-08-24 a 21 06 27" src="https://cloud.githubusercontent.com/assets/3610253/17944139/c01c7a72-6a3e-11e6-9ddf-86fb5e03828a.png">

**Comment by sunng87** [comment]
No, this is not supported at the moment.

**Comment by sunng87** [comment]
This should be fixed in 0.20.4, via 877f303

**Comment by Kerosene2000** [comment]
That's really great ! thx 😸
